from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class ReasoningDepthDecision(BaseModel):
    tier: Literal["fast_admin", "fast_faq", "targeted_rag", "exhaustive_discovery", "high_risk_handoff"]
    requires_full_context: bool = True
    requires_rag: bool = True
    requires_exhaustive_schedule2: bool = False
    requires_live_official_check: bool = True
    requires_candidate_comparison: bool = False
    reason: str


class ReasoningDepthRouter:
    """Deprecated fallback only.

    The main runtime no longer uses this as a pre-GPT router. Verification depth is
    generated by the first backend GPT proposal call. This class remains only for
    emergency compatibility with older imports and deliberately avoids
    case-specific visa regex rules.
    """

    def classify(self, *, memory_packet: object, current_state: object | None = None) -> ReasoningDepthDecision:
        return ReasoningDepthDecision(
            tier="targeted_rag",
            requires_full_context=True,
            requires_rag=True,
            requires_exhaustive_schedule2=False,
            requires_live_official_check=True,
            requires_candidate_comparison=False,
            reason="deprecated_fallback_only__gpt_proposal_now_produces_verification_plan",
        )
