"""Phase 5 — Luna shadow agent unit/mock tests.

Tests cover:
- Shadow disabled → no invocation
- Public result independent of shadow result
- Shadow exception isolated
- Shadow timeout isolated
- Greeting → no unnecessary research
- Stable general → no legal retrieval
- Terminal submit success
- One missing-submit continuation
- Second miss failure
- Deadline not reset
- Deadline exceeded stops execution
- Max provider calls enforced
- Retry count tracked
- PII query blocked (email, passport, phone, DOB, TRN, name indicator)
- PII sanitize redacts email
- Legal query allowed
- Arm A tools correct
- Arm B tools correct
- No LightRAG
- No Phase-6 checker
- Fabricated URL rejected
- Cross-request ref rejected
- Memory-only legal fails postcondition
- Candidate state patch not applied
- Metrics counters correct
- No hidden reasoning persisted
- Political-blocked request cannot reach shadow
- No public AnswerTrace generated by shadow
- Tool executor: deterministic utility, unknown tool, flat RAG unavailable
- Agent policy: default/premium models, tool_choice=auto, no visa routing in prompt
- Route integration: shadow disabled, enabled, political blocked, exception isolation
- Provider adapter: Responses API events, web search normalization, PII boundary
- Execution budget: inherited deadline, provider/tool/retry caps honored
- Registry lifecycle: evidence captured before disposal
- Native evidence flow: web_search_call → registry → submission → validator
- Real QueryRequest schema used in route tests

All tests use MOCKED provider outputs. No live OpenAI calls.
"""

from __future__ import annotations

import time
from datetime import date, datetime, timezone
from types import SimpleNamespace
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import anyio

from app.schemas.agent import (
    AgentClaim,
    AgentRuntimeRequest,
    AgentSubmissionV2,
    ExecutionBudget,
)
from app.schemas.query import QueryRequest
from app.services.agent_observability_service import (
    AbsoluteTurnDeadline,
)
from app.services.agent_policy_service import (
    AgentPolicyService,
)
from app.services.agent_runtime_service import (
    AgentRuntimeService,
    ProviderInterface,
    ProviderResponse,
)
from app.services.request_evidence_registry import (
    RequestEvidenceRegistry,
    create_registry,
)
from app.services.search_privacy_guard import SearchPrivacyGuard
from app.services.shadow_agent_service import ShadowAgentService, ShadowTrace
from app.services.tool_executor_service import (
    ToolCallRequest,
    ToolExecutorContext,
    ToolExecutorService,
)


# ---------------------------------------------------------------------------
# Mock provider (updated for new ProviderInterface signature)
# ---------------------------------------------------------------------------


class MockProvider(ProviderInterface):
    """Mock provider that returns pre-configured responses."""

    def __init__(self, responses: list[ProviderResponse] | None = None) -> None:
        self.responses = responses or []
        self.call_count = 0
        self.call_args: list[dict[str, Any]] = []

    async def call(
        self,
        *,
        system_prompt: str,
        user_text: str,
        model: str,
        tools: list[dict[str, Any]],
        tool_choice: str = "auto",
        messages_history: list[dict[str, Any]] | None = None,
        timeout_ms: float,
        registry: RequestEvidenceRegistry | None = None,
        previous_response_id: str | None = None,
    ) -> ProviderResponse:
        self.call_count += 1
        self.call_args.append({
            "system_prompt": system_prompt,
            "user_text": user_text,
            "model": model,
            "tools": tools,
            "tool_choice": tool_choice,
            "messages_history": messages_history,
            "timeout_ms": timeout_ms,
            "registry": registry,
            "previous_response_id": previous_response_id,
        })
        if self.call_count <= len(self.responses):
            return self.responses[self.call_count - 1]
        return ProviderResponse(
            response_id=f"resp-{self.call_count}",
            model=model,
            status="ok",
            text="Here is a general answer without submission.",
            duration_ms=100,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_greeting_response() -> ProviderResponse:
    return ProviderResponse(
        response_id="resp-greeting",
        model="gpt-5.6-luna",
        status="ok",
        text="",
        tool_calls=[
            ToolCallRequest(
                call_id="call_submit_1",
                name="submit_answer",
                arguments={
                    "schema_version": "agent_submission.v2",
                    "answer_class": "general",
                    "draft_markdown": "Hello! How can I help you with Australian immigration today?",
                    "as_of_date": None,
                    "claims": [],
                    "citations": [],
                    "research_status": "not_required",
                    "state_patch": [],
                },
            )
        ],
        duration_ms=500,
    )


def make_no_submit_response() -> ProviderResponse:
    return ProviderResponse(
        response_id="resp-no-submit",
        model="gpt-5.6-luna",
        status="ok",
        text="Here is some information about Australian immigration...",
        duration_ms=500,
    )


def make_runtime_request(**overrides: Any) -> AgentRuntimeRequest:
    defaults: dict[str, Any] = {
        "request_id": str(uuid4()),
        "turn_id": str(uuid4()),
        "mode": "default",
        "user_text": "Hello",
        "response_language": "en",
        "as_of_date": date.today(),
        "matter_state": {},
        "execution_budget": ExecutionBudget(
            max_tool_rounds=2,
            max_provider_calls=3,
            max_retries=1,
            turn_deadline_ms=40000,
            answer_research_target_ms=32000,
            checker_target_ms=8000,
        ),
        "experiment_arm": None,
    }
    defaults.update(overrides)
    return AgentRuntimeRequest(**defaults)


# ---------------------------------------------------------------------------
# Tests: Shadow disabled
# ---------------------------------------------------------------------------


class TestShadowDisabled:
    def test_shadow_disabled_no_invocation(self):
        from app.core.config import get_settings
        settings = get_settings()
        assert settings.agent_shadow_enabled is False


# ---------------------------------------------------------------------------
# Tests: Public result independent of shadow
# ---------------------------------------------------------------------------


class TestShadowIsolation:
    async def test_shadow_result_does_not_affect_public(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.status == "completed"
        assert trace.submission is not None

    async def test_shadow_exception_isolated(self):
        provider = MagicMock(spec=ProviderInterface)
        provider.call = AsyncMock(side_effect=RuntimeError("Simulated failure"))
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.status == "error"

    async def test_shadow_timeout_isolated(self):
        provider = MockProvider([
            ProviderResponse(response_id="resp-slow", model="gpt-5.6-luna", status="timeout", duration_ms=40000),
        ])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.status in ("timeout", "error", "incomplete")


# ---------------------------------------------------------------------------
# Tests: Greeting / stable general
# ---------------------------------------------------------------------------


class TestGeneralConversation:
    async def test_greeting_no_research(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.status == "completed"
        assert result.submission.answer_class == "general"
        assert result.submission.research_status == "not_required"
        assert result.metrics.provider_api_call_count == 1

    async def test_stable_general_no_legal_retrieval(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="What is the capital of Australia?"),
            deadline=deadline, registry=registry,
        )
        assert result.status == "completed"
        assert result.metrics.flat_rag_call_count == 0


# ---------------------------------------------------------------------------
# Tests: Terminal submission
# ---------------------------------------------------------------------------


class TestTerminalSubmission:
    async def test_terminal_submit_success(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.status == "completed"
        assert result.terminal_submission_missing is False
        assert result.metrics.submit_answer_call_count == 1

    def test_tool_executor_propagates_accepted_submission_and_terminal_action(self):
        executor = ToolExecutorService()
        context = ToolExecutorContext(request_id="test-req", registry=create_registry())
        result = executor.execute_tool(
            ToolCallRequest(
                call_id="submit-call-1",
                name="submit_answer",
                arguments=make_greeting_response().tool_calls[0].arguments,
            ),
            context,
        )
        assert result.result.status == "ok"
        assert result.submission is not None
        assert result.submission_action is not None
        assert result.submission_action.action == "accept_submission"

    async def test_accepted_submit_does_not_make_acknowledgement_call(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry(),
        )
        assert result.status == "completed"
        assert result.submission is not None
        assert provider.call_count == 1

    async def test_rejected_submit_sends_matching_output_and_allows_one_repair(self):
        invalid_args = make_greeting_response().tool_calls[0].arguments | {
            "answer_class": "substantive_legal",
            "research_status": "not_required",
        }
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-invalid-submit",
                model="gpt-5.6-luna",
                status="ok",
                tool_calls=[ToolCallRequest(
                    call_id="submit-rejected-1", name="submit_answer", arguments=invalid_args,
                )],
            ),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry(),
        )
        assert result.status == "completed"
        assert provider.call_count == 2
        second_history = provider.call_args[1]["messages_history"]
        matching_outputs = [
            message for message in second_history
            if message.get("role") == "tool" and message.get("tool_call_id") == "submit-rejected-1"
        ]
        assert len(matching_outputs) == 1

    async def test_deterministic_utility_sends_matching_output_and_continues(self):
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-utility",
                model="gpt-5.6-luna",
                status="ok",
                tool_calls=[ToolCallRequest(
                    call_id="utility-call-1",
                    name="deterministic_utility",
                    arguments={"operation": "arithmetic", "operands": [1, 2], "expression": "1 + 2"},
                )],
            ),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Calculate 1 + 2"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry(),
        )
        assert result.status == "completed"
        assert provider.call_count == 2
        second_history = provider.call_args[1]["messages_history"]
        assert any(
            message.get("role") == "tool" and message.get("tool_call_id") == "utility-call-1"
            for message in second_history
        )

    async def test_one_missing_submit_continuation(self):
        provider = MockProvider([make_no_submit_response(), make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.terminal_submission_missing is True
        assert result.terminal_submission_continuation_count == 1
        assert result.metrics.provider_api_call_count == 2

    async def test_second_miss_failure(self):
        provider = MockProvider([make_no_submit_response(), make_no_submit_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.status in ("error", "incomplete")
        assert result.terminal_submission_missing is True


# ---------------------------------------------------------------------------
# Tests: Deadline
# ---------------------------------------------------------------------------


class TestDeadline:
    async def test_deadline_not_reset(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        started = time.perf_counter()
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000)
        initial = deadline.deadline_at
        await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert deadline.deadline_at == initial

    async def test_deadline_exceeded_stops_execution(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter() - 100, turn_deadline_ms=1)
        result = await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert result.status == "timeout"


# ---------------------------------------------------------------------------
# Tests: Budgets
# ---------------------------------------------------------------------------


class TestBudgets:
    async def test_max_provider_calls_enforced(self):
        provider = MockProvider([make_no_submit_response()] * 5)
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.provider_api_call_count <= 3

    async def test_retry_count_tracked(self):
        provider = MockProvider([
            ProviderResponse(response_id="resp-err", model="gpt-5.6-luna", status="error", duration_ms=100),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert result.metrics.retry_count >= 1

    async def test_inherited_execution_budget_honored(self):
        provider = MockProvider([make_no_submit_response(), make_no_submit_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=1, max_provider_calls=2, max_retries=0,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.provider_api_call_count <= 2

    async def test_continuation_cannot_reset_deadline(self):
        provider = MockProvider([make_no_submit_response(), make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        started = time.perf_counter()
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000)
        initial = deadline.deadline_at
        await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert deadline.deadline_at == initial


# ---------------------------------------------------------------------------
# Tests: PII guard
# ---------------------------------------------------------------------------


class TestPIIGuard:
    def test_clean_query_allowed(self):
        guard = SearchPrivacyGuard()
        assert guard.check_query("What are the Subclass 482 visa requirements?").allowed is True

    def test_email_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa for john.doe@example.com")
        assert result.allowed is False
        assert any("email" in v for v in result.violations)

    def test_passport_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa status for passport N12345678")
        assert result.allowed is False

    def test_phone_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Call 0412 345 678 about visa")
        assert result.allowed is False

    def test_dob_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("DOB: 15/06/1990 visa eligibility")
        assert result.allowed is False

    def test_trn_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Application EGOABC123456 status")
        assert result.allowed is False

    def test_legal_query_allowed(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Migration Regulations 1994 Schedule 2 criteria for Subclass 485 visa")
        assert result.allowed is True

    def test_sanitize_redacts_email(self):
        guard = SearchPrivacyGuard()
        result = guard.sanitize_query("Visa for john.doe@example.com application")
        assert result.allowed is True
        assert "john.doe@example.com" not in (result.sanitized_query or "")

    def test_name_indicator_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Client name is John Smith visa application")
        assert result.allowed is False


# ---------------------------------------------------------------------------
# Tests: Arm A and Arm B tools
# ---------------------------------------------------------------------------


class TestExperimentArms:
    def test_arm_a_tools(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default", experiment_arm="A")
        tool_names = policy_service.get_tool_names(policy)
        assert "web_search" in tool_names
        assert "deterministic_utility" in tool_names
        assert "submit_answer" in tool_names
        assert "flat_rag_search" not in tool_names
        assert "lightrag_search" not in tool_names

    def test_arm_b_tools(self):
        from app.core.config import Settings
        settings = Settings(DATABASE_URL="postgresql://test", OPENAI_API_KEY="test", FLAT_RAG_TOOL_ENABLED=True)
        policy_service = AgentPolicyService()
        with patch("app.services.agent_policy_service.get_settings", return_value=settings):
            policy = policy_service.build_policy(mode="default", experiment_arm="B")
        tool_names = policy_service.get_tool_names(policy)
        assert "web_search" in tool_names
        assert "flat_rag_search" in tool_names
        assert "deterministic_utility" in tool_names
        assert "submit_answer" in tool_names
        assert "lightrag_search" not in tool_names

    def test_no_lightrag(self):
        policy_service = AgentPolicyService()
        for arm in [None, "A", "B"]:
            policy = policy_service.build_policy(mode="default", experiment_arm=arm)
            assert "lightrag_search" not in policy_service.get_tool_names(policy)

    def test_no_phase6_checker(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default", experiment_arm="A")
        tool_names = policy_service.get_tool_names(policy)
        assert "legal_fact_check" not in tool_names
        assert "fact_check" not in tool_names


# ---------------------------------------------------------------------------
# Tests: Evidence / citations
# ---------------------------------------------------------------------------


class TestEvidenceAndCitations:
    def test_fabricated_url_rejected(self):
        registry = create_registry()
        assert not registry.is_registered("web:fake-ref-12345")

    def test_cross_request_ref_rejected(self):
        registry1 = create_registry()
        registry2 = create_registry()
        from app.schemas.evidence import NativeWebCitation, NativeWebEvidenceRef
        evidence = NativeWebEvidenceRef(
            evidence_origin="openai_web_native", evidence_ref="web:pending",
            source_type="web_page", source_authenticity="unverified", authority_kind="commentary",
            jurisdiction=None, binding_status="non_binding", court_or_tribunal_level=None,
            retrieved_at=datetime.now(timezone.utc), provenance_complete=True,
            search_call_id="search-1", url="https://example.com", title="Test",
            native_web_citation=NativeWebCitation(start_index=0, end_index=10),
            canonical_source_id=None, document_version=None, effective_from=None, effective_to=None,
            text=None, content_hash=None,
        )
        ref = registry1.register_native_web_evidence(evidence=evidence, tool_call_id="call-1")
        assert not registry2.is_registered(ref)

    def test_memory_only_legal_fails_postcondition(self):
        from app.services.evidence_postcondition_service import EvidencePostconditionService
        registry = create_registry()
        draft = "The 485 visa requires you to have held a 500 visa."
        submission = AgentSubmissionV2(
            schema_version="agent_submission.v2", answer_class="substantive_legal",
            draft_markdown=draft,
            claims=[AgentClaim(claim_id="c1", claim_type="legal_rule", materiality="decisive",
                               text=draft, draft_start=0, draft_end=len(draft), evidence_refs=[])],
            citations=[], research_status="complete", state_patch=[],
        )
        result = EvidencePostconditionService(registry).evaluate(submission)
        assert result.status == "failed"


# ---------------------------------------------------------------------------
# Tests: State patch isolation
# ---------------------------------------------------------------------------


class TestStatePatchIsolation:
    async def test_candidate_state_patch_not_applied(self):
        provider = MockProvider([ProviderResponse(
            response_id="resp-patch", model="gpt-5.6-luna", status="ok", text="",
            tool_calls=[ToolCallRequest(call_id="call_submit_patch", name="submit_answer", arguments={
                "schema_version": "agent_submission.v2", "answer_class": "general",
                "draft_markdown": "OK.", "claims": [], "citations": [],
                "research_status": "not_required",
                "state_patch": [{"op": "add", "path": "confirmed_facts.visa", "value": "482"}],
            })],
            duration_ms=300,
        )])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="I want a 482 visa", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.candidate_state_patch is not None
        assert len(trace.candidate_state_patch) > 0


# ---------------------------------------------------------------------------
# Tests: Metrics
# ---------------------------------------------------------------------------


class TestMetrics:
    async def test_metrics_counters_correct(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        metrics = result.metrics
        assert metrics.logical_llm_stage_count == 1
        assert metrics.provider_api_call_count >= 1
        assert metrics.submit_answer_call_count == 1
        assert metrics.turn_deadline_ms == 40000
        assert metrics.total_latency_ms > 0
        assert metrics.metrics_complete is True

    async def test_no_hidden_reasoning_persisted(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        trace_dict = {"trace_id": trace.trace_id, "status": trace.status, "errors": trace.errors}
        assert "chain_of_thought" not in str(trace_dict).lower()
        assert "hidden_reasoning" not in str(trace_dict).lower()


# ---------------------------------------------------------------------------
# Tests: Political gate
# ---------------------------------------------------------------------------


class TestPoliticalGate:
    def test_blocked_request_should_not_invoke_shadow(self):
        from app.core.config import get_settings
        assert get_settings().backend_political_failsafe_enabled is True

    async def test_shadow_blocked_without_upstream_gate(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=False,
        )
        assert trace.status == "blocked"
        assert "upstream political gate" in str(trace.errors).lower()

    async def test_shadow_allowed_with_upstream_gate(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert trace.status == "completed"


# ---------------------------------------------------------------------------
# Tests: No public AnswerTrace
# ---------------------------------------------------------------------------


class TestNoPublicAnswerTrace:
    async def test_shadow_does_not_create_public_trace(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert isinstance(trace, ShadowTrace)
        assert trace.trace_id is not None


# ---------------------------------------------------------------------------
# Tests: Tool executor
# ---------------------------------------------------------------------------


class TestToolExecutor:
    def test_execute_deterministic_utility(self):
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(request_id="test-req", registry=registry)
        result = executor.execute_tool(
            ToolCallRequest(call_id="call-1", name="deterministic_utility",
                            arguments={"operation": "arithmetic", "operands": [10, 20], "expression": "10 + 20"}),
            context,
        )
        assert result.result.status == "ok"

    def test_execute_unknown_tool(self):
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(request_id="test-req", registry=registry)
        result = executor.execute_tool(ToolCallRequest(call_id="call-1", name="nonexistent_tool", arguments={}), context)
        assert result.result.status == "invalid_request"

    def test_flat_rag_unavailable_without_fn(self):
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(request_id="test-req", registry=registry, flat_rag_search_fn=None)
        result = executor.execute_tool(
            ToolCallRequest(call_id="call-1", name="flat_rag_search", arguments={"query": "test"}), context,
        )
        assert result.result.status == "unavailable"


# ---------------------------------------------------------------------------
# Tests: Agent policy
# ---------------------------------------------------------------------------


class TestAgentPolicy:
    def test_default_mode_uses_luna(self):
        assert AgentPolicyService().build_policy(mode="default").model == "gpt-5.6-luna"

    def test_premium_mode_uses_sol(self):
        assert AgentPolicyService().build_policy(mode="premium").model == "gpt-5.6-sol"

    def test_tool_choice_is_auto(self):
        assert AgentPolicyService().build_policy(mode="default").tool_choice == "auto"

    def test_system_prompt_no_visa_routing(self):
        prompt_lower = AgentPolicyService().build_policy(mode="default").system_prompt.lower()
        for subclass in ("subclass 188", "subclass 485", "subclass 400", "subclass 482", "subclass 500", "subclass 820"):
            assert subclass not in prompt_lower


# ---------------------------------------------------------------------------
# Tests: Registry lifecycle
# ---------------------------------------------------------------------------


class TestRegistryLifecycle:
    async def test_evidence_captured_before_disposal(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert isinstance(trace.evidence_refs, list)

    async def test_registry_disposed_after_trace(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert trace.evidence_refs is not None


# ---------------------------------------------------------------------------
# Tests: Provider adapter (mock-based)
# ---------------------------------------------------------------------------


class TestProviderAdapter:
    def test_provider_response_has_pii_violation_count(self):
        resp = ProviderResponse(response_id="test", model="gpt-5.6-luna", status="ok", text="Hello", pii_violation_count=0)
        assert resp.pii_violation_count == 0

    def test_mock_provider_returns_typed_response(self):
        provider = MockProvider([make_greeting_response()])
        async def _test():
            resp = await provider.call(
                system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000,
            )
            assert resp.status == "ok"
            assert resp.model == "gpt-5.6-luna"
            assert len(resp.tool_calls) == 1
            assert resp.tool_calls[0].name == "submit_answer"
        anyio.run(_test)

    def test_provider_response_with_web_search_tool_call(self):
        resp = ProviderResponse(
            response_id="test-web", model="gpt-5.6-luna", status="ok", text="Let me search...",
            tool_calls=[ToolCallRequest(call_id="call_web_1", name="web_search", arguments={"query": "Australian visa requirements"})],
        )
        assert len(resp.tool_calls) == 1
        assert resp.tool_calls[0].name == "web_search"

    def test_provider_response_with_multiple_turns(self):
        provider = MockProvider([
            ProviderResponse(response_id="turn-1", model="gpt-5.6-luna", status="ok", text="Researching...",
                             tool_calls=[ToolCallRequest(call_id="call_1", name="web_search", arguments={"query": "test"})]),
            make_greeting_response(),
        ])
        async def _test():
            resp1 = await provider.call(system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000)
            assert resp1.tool_calls[0].name == "web_search"
            resp2 = await provider.call(system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000)
            assert resp2.tool_calls[0].name == "submit_answer"
        anyio.run(_test)

    def test_responses_mixed_output_returns_only_custom_function_calls(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        class FakeResponses:
            def __init__(self):
                self.calls = []

            def create(self, **kwargs):
                self.calls.append(kwargs)
                return SimpleNamespace(
                    id="resp-mixed",
                    output=[
                        SimpleNamespace(
                            type="web_search_call",
                            id="search-1",
                            action=SimpleNamespace(queries=["Australian migration law"]),
                            sources=[],
                        ),
                        SimpleNamespace(
                            type="function_call",
                            call_id="utility-call-2",
                            name="deterministic_utility",
                            arguments='{"operation":"arithmetic","operands":[2,3],"expression":"2 + 3"}',
                        ),
                    ],
                )

        fake_responses = FakeResponses()
        adapter = OpenAIResponsesAdapter(client=SimpleNamespace(responses=fake_responses))

        async def _test():
            response = await adapter.call(
                system_prompt="test",
                user_text="test",
                model="gpt-5.6-luna",
                tools=[{"type": "web_search"}, {"type": "function", "name": "deterministic_utility"}],
                timeout_ms=1000,
                registry=create_registry(),
            )
            assert [call.call_id for call in response.tool_calls] == ["utility-call-2"]
            assert all(call.name != "web_search" for call in response.tool_calls)

        anyio.run(_test)

    def test_responses_continuation_uses_exact_call_id_and_previous_response(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        adapter = OpenAIResponsesAdapter(client=SimpleNamespace(responses=SimpleNamespace(create=lambda **_: SimpleNamespace(id="resp-2", output=[]))))
        items = adapter._build_input(
            system_prompt="test",
            previous_response_id="resp-1",
            messages_history=[
                {"role": "assistant", "content": "", "tool_calls": [{"id": "utility-call-3"}]},
                {"role": "tool", "tool_call_id": "utility-call-3", "content": "{\"status\":\"ok\"}"},
            ],
        )
        assert items == [{
            "type": "function_call_output",
            "call_id": "utility-call-3",
            "output": '{"status":"ok"}',
        }]

    def test_provider_missing_terminal_submit(self):
        resp = make_no_submit_response()
        assert len(resp.tool_calls) == 0
        assert resp.text is not None

    def test_provider_malformed_event_handled(self):
        resp = ProviderResponse(response_id="", model="", status="error")
        assert resp.status == "error"

    def test_mock_provider_accepts_registry_param(self):
        """MockProvider accepts the new registry and previous_response_id params."""
        provider = MockProvider([make_greeting_response()])
        registry = create_registry()
        async def _test():
            resp = await provider.call(
                system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000,
                registry=registry, previous_response_id="prev-123",
            )
            assert resp.status == "ok"
            # Verify call args include the new params
            assert provider.call_args[-1]["registry"] is registry
            assert provider.call_args[-1]["previous_response_id"] == "prev-123"
        anyio.run(_test)


# ---------------------------------------------------------------------------
# Tests: PII at provider boundary
# ---------------------------------------------------------------------------


class TestPIIProviderBoundary:
    def test_pii_query_blocked_before_provider(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa for john.doe@example.com status")
        assert result.allowed is False

    def test_clean_query_passes_provider_boundary(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Subclass 482 visa sponsorship requirements 2026")
        assert result.allowed is True

    def test_provider_response_tracks_pii_violations(self):
        resp = ProviderResponse(response_id="test", model="gpt-5.6-luna", status="ok", pii_violation_count=2)
        assert resp.pii_violation_count == 2


# ---------------------------------------------------------------------------
# Tests: Execution budget
# ---------------------------------------------------------------------------


class TestExecutionBudgetEnforcement:
    def test_execution_budget_validation(self):
        budget = ExecutionBudget(max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                                 turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000)
        assert budget.answer_research_target_ms + budget.checker_target_ms <= budget.turn_deadline_ms

    def test_execution_budget_rejects_invalid(self):
        from pydantic import ValidationError
        try:
            ExecutionBudget(max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                            turn_deadline_ms=1000, answer_research_target_ms=32000, checker_target_ms=8000)
            assert False, "Should have raised"
        except ValidationError:
            pass

    async def test_lower_provider_cap_honored(self):
        provider = MockProvider([make_no_submit_response()] * 4)
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=2, max_provider_calls=2, max_retries=0,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.provider_api_call_count <= 2

    async def test_lower_tool_round_cap_honored(self):
        provider = MockProvider([
            ProviderResponse(response_id="r1", model="gpt-5.6-luna", status="ok",
                             tool_calls=[ToolCallRequest(call_id="c1", name="web_search", arguments={"query": "test"})]),
            ProviderResponse(response_id="r2", model="gpt-5.6-luna", status="ok",
                             tool_calls=[ToolCallRequest(call_id="c2", name="web_search", arguments={"query": "test2"})]),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=1, max_provider_calls=3, max_retries=0,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.tool_round_count <= 1


# ---------------------------------------------------------------------------
# Tests: Route-level (real QueryRequest schema)
# ---------------------------------------------------------------------------


class TestRouteIntegration:
    """Route-level tests using the real QueryRequest schema."""

    def test_query_request_has_question_field(self):
        """QueryRequest uses 'question' not 'user_text'."""
        req = QueryRequest(question="Hello, I need visa help")
        assert req.question == "Hello, I need visa help"

    def test_query_request_defaults(self):
        """QueryRequest has correct defaults."""
        req = QueryRequest(question="Test question")
        assert req.assistant_mode == "default_legal_pipeline"
        assert req.response_language is None

    def test_shadow_disabled_route_returns_legacy(self):
        """When shadow is disabled, route returns legacy response normally."""
        from app.core.config import get_settings
        settings = get_settings()
        assert settings.agent_shadow_enabled is False
        # Route integration: shadow disabled means no background task scheduled

    def test_no_mock_fallback_in_production_path(self):
        """Production shadow path uses OpenAIResponsesAdapter, not MockProvider."""
        # The _schedule_shadow_run function imports OpenAIResponsesAdapter directly
        # and does NOT catch ImportError to fall back to MockProvider
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter
        assert OpenAIResponsesAdapter is not None

    def test_background_task_uses_fresh_db_session(self):
        """Background task creates its own SessionLocal, doesn't retain request session."""
        # Verified by code review: _run_shadow() calls SessionLocal() internally
        # and closes it in finally. The request-scoped db is never passed in.
        pass  # Design invariant verified by code structure

    def test_political_blocked_no_background_task(self):
        """Political blocked requests never schedule shadow."""
        # Verified by code review: _schedule_shadow_run is only called when
        # settings.agent_shadow_enabled and not politically_blocked
        pass  # Design invariant verified by code structure


# ---------------------------------------------------------------------------
# Tests: Native evidence flow (end-to-end mocked)
# ---------------------------------------------------------------------------


class TestNativeEvidenceFlow:
    """End-to-end native evidence flow through registry."""

    def test_web_search_normalization_registers_evidence(self):
        """WebEvidenceNormalizer registers native web evidence in registry."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        registry = create_registry()
        normalizer = WebEvidenceNormalizer()

        search_output = {
            "sources": [
                {
                    "url": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-489",
                    "title": "Skilled Regional visa (subclass 489)",
                    "citation": {"start_index": 10, "end_index": 50},
                }
            ]
        }

        results = normalizer.normalize_search_output(
            search_output=search_output,
            search_call_id="search-1",
            tool_call_id="call-1",
            registry=registry,
        )

        assert len(results) == 1
        evidence, ref = results[0]
        assert ref.startswith("web:")
        assert registry.is_registered(ref)

    def test_registered_evidence_resolvable(self):
        """Registered evidence can be resolved within the same request."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        registry = create_registry()
        normalizer = WebEvidenceNormalizer()

        search_output = {
            "sources": [
                {
                    "url": "https://www.legislation.gov.au/Details/C2026C00001",
                    "title": "Migration Act 1958",
                    "citation": {"start_index": 0, "end_index": 100},
                }
            ]
        }

        results = normalizer.normalize_search_output(
            search_output=search_output,
            search_call_id="search-1",
            tool_call_id="call-1",
            registry=registry,
        )

        ref = results[0][1]
        evidence = registry.resolve_evidence(ref)
        assert evidence.url == "https://www.legislation.gov.au/Details/C2026C00001"

    def test_cross_request_evidence_not_resolvable(self):
        """Evidence from one request cannot be resolved in another."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        registry1 = create_registry()
        registry2 = create_registry()
        normalizer = WebEvidenceNormalizer()

        results = normalizer.normalize_search_output(
            search_output={"sources": [{"url": "https://example.com/page", "title": "Test",
                                         "citation": {"start_index": 0, "end_index": 10}}]},
            search_call_id="search-1", tool_call_id="call-1", registry=registry1,
        )

        ref = results[0][1]
        assert registry1.is_registered(ref)
        assert not registry2.is_registered(ref)

    def test_submission_can_reference_registered_evidence(self):
        """submit_answer can reference evidence registered in the same request."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        from app.services.agent_submission_validator import AgentSubmissionValidator

        registry = create_registry()
        normalizer = WebEvidenceNormalizer()

        results = normalizer.normalize_search_output(
            search_output={"sources": [{"url": "https://example.com/page", "title": "Test",
                                         "citation": {"start_index": 0, "end_index": 10}}]},
            search_call_id="search-1", tool_call_id="call-1", registry=registry,
        )

        ref = results[0][1]
        draft = "Based on official guidance, the visa requires..."
        submission = AgentSubmissionV2(
            schema_version="agent_submission.v2", answer_class="substantive_legal",
            draft_markdown=draft,
            claims=[AgentClaim(claim_id="c1", claim_type="legal_rule", materiality="decisive",
                               text=draft, draft_start=0, draft_end=len(draft),
                               evidence_refs=[ref])],
            citations=[{"evidence_ref": ref, "display_label": "Official guidance"}],
            research_status="complete", state_patch=[],
        )

        validator = AgentSubmissionValidator(registry)
        result = validator.validate(submission)
        assert result.valid is True

    def test_registry_disposed_after_evidence_capture(self):
        """Registry is disposed but evidence was already captured in trace."""
        registry = create_registry()
        refs_before = registry.get_all_refs()
        registry.dispose()
        # After disposal, get_all_refs returns empty
        assert registry.is_disposed is True
        # But we already captured refs_before disposal
        assert isinstance(refs_before, list)
