"""Phase 5 — Luna shadow agent unit/mock tests.

Tests cover:
- Shadow disabled → no invocation
- Public result independent of shadow result
- Shadow exception isolated
- Shadow timeout isolated
- Greeting → no unnecessary research
- Stable general → no legal retrieval
- Terminal submit success
- One missing-submit continuation
- Second miss failure
- Deadline not reset
- Deadline exceeded stops execution
- Max provider calls enforced
- Retry count tracked
- PII query blocked (email, passport, phone, DOB, TRN, name indicator)
- PII sanitize redacts email
- Legal query allowed
- Arm A tools correct
- Arm B tools correct
- No LightRAG
- No Phase-6 checker
- Fabricated URL rejected
- Cross-request ref rejected
- Memory-only legal fails postcondition
- Candidate state patch not applied
- Metrics counters correct
- No hidden reasoning persisted
- Political-blocked request cannot reach shadow
- No public AnswerTrace generated by shadow
- Tool executor: deterministic utility, unknown tool, flat RAG unavailable
- Agent policy: default/premium models, tool_choice=auto, no visa routing in prompt
- Route integration: shadow disabled, enabled, political blocked, exception isolation
- Provider adapter: Responses API events, web search normalization, PII boundary
- Execution budget: inherited deadline, provider/tool/retry caps honored
- Registry lifecycle: evidence captured before disposal
- Native evidence flow: web_search_call → registry → submission → validator
- Real QueryRequest schema used in route tests

All tests use MOCKED provider outputs. No live OpenAI calls.
"""

from __future__ import annotations

import json
import time
from datetime import date, datetime, timezone
from types import SimpleNamespace
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import anyio

from app.schemas.agent import (
    AgentClaim,
    AgentRuntimeRequest,
    AgentSubmissionV2,
    ExecutionBudget,
)
from app.schemas.query import QueryRequest
from app.services.agent_observability_service import (
    AbsoluteTurnDeadline,
)
from app.services.agent_policy_service import (
    AgentPolicyService,
)
from app.services.agent_runtime_service import (
    AgentRuntimeService,
    ProviderInterface,
    ProviderResponse,
)
from app.services.request_evidence_registry import (
    RequestEvidenceRegistry,
    create_registry,
)
from app.services.search_privacy_guard import SearchPrivacyGuard
from app.services.shadow_agent_service import ShadowAgentService, ShadowTrace
from app.services.tool_executor_service import (
    ToolCallRequest,
    ToolExecutorContext,
    ToolExecutorService,
)


# ---------------------------------------------------------------------------
# Mock provider (updated for new ProviderInterface signature)
# ---------------------------------------------------------------------------


class MockProvider(ProviderInterface):
    """Mock provider that returns pre-configured responses."""

    def __init__(self, responses: list[ProviderResponse] | None = None) -> None:
        self.responses = responses or []
        self.call_count = 0
        self.call_args: list[dict[str, Any]] = []

    async def call(
        self,
        *,
        system_prompt: str,
        user_text: str,
        model: str,
        tools: list[dict[str, Any]],
        tool_choice: str = "auto",
        reasoning_effort: str | None = None,
        messages_history: list[dict[str, Any]] | None = None,
        timeout_ms: float,
        registry: RequestEvidenceRegistry | None = None,
        previous_response_id: str | None = None,
    ) -> ProviderResponse:
        self.call_count += 1
        self.call_args.append({
            "system_prompt": system_prompt,
            "user_text": user_text,
            "model": model,
            "tools": tools,
            "tool_choice": tool_choice,
            "reasoning_effort": reasoning_effort,
            "messages_history": messages_history,
            "timeout_ms": timeout_ms,
            "registry": registry,
            "previous_response_id": previous_response_id,
        })
        if self.call_count <= len(self.responses):
            return self.responses[self.call_count - 1]
        return ProviderResponse(
            response_id=f"resp-{self.call_count}",
            model=model,
            status="ok",
            text="Here is a general answer without submission.",
            duration_ms=100,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_greeting_response() -> ProviderResponse:
    return ProviderResponse(
        response_id="resp-greeting",
        model="gpt-5.6-luna",
        status="ok",
        text="",
        tool_calls=[
            ToolCallRequest(
                call_id="call_submit_1",
                name="submit_answer",
                arguments={
                    "schema_version": "agent_submission.v2",
                    "answer_class": "general",
                    "draft_markdown": "Hello! How can I help you with Australian immigration today?",
                    "as_of_date": None,
                    "claims": [],
                    "citations": [],
                    "research_status": "not_required",
                    "state_patch": [],
                },
            )
        ],
        duration_ms=500,
    )


def make_no_submit_response() -> ProviderResponse:
    return ProviderResponse(
        response_id="resp-no-submit",
        model="gpt-5.6-luna",
        status="ok",
        text="Here is some information about Australian immigration...",
        duration_ms=500,
    )


def make_runtime_request(**overrides: Any) -> AgentRuntimeRequest:
    defaults: dict[str, Any] = {
        "request_id": str(uuid4()),
        "turn_id": str(uuid4()),
        "mode": "default",
        "user_text": "Hello",
        "response_language": "en",
        "as_of_date": date.today(),
        "matter_state": {},
        "execution_budget": ExecutionBudget(
            max_tool_rounds=2,
            max_provider_calls=3,
            max_retries=1,
            turn_deadline_ms=40000,
            answer_research_target_ms=32000,
            checker_target_ms=8000,
        ),
        "experiment_arm": None,
    }
    defaults.update(overrides)
    return AgentRuntimeRequest(**defaults)


def make_submit_context() -> ToolExecutorContext:
    return ToolExecutorContext(request_id="span-test", registry=create_registry("span-test"))


def make_submit_call(*, draft: str, claim_text: str, start: int, end: int) -> ToolCallRequest:
    return ToolCallRequest(
        call_id="submit-span-test",
        name="submit_answer",
        arguments={
            "schema_version": "agent_submission.v2",
            "answer_class": "general",
            "draft_markdown": draft,
            "as_of_date": None,
            "claims": [{
                "claim_id": "c1",
                "claim_type": "general",
                "materiality": "supporting",
                "text": claim_text,
                "draft_start": start,
                "draft_end": end,
                "evidence_refs": [],
            }],
            "citations": [],
            "research_status": "not_required",
            "state_patch": [],
        },
    )


class TestClaimSpanNormalization:
    def test_valid_model_offsets_are_preserved(self):
        draft = "A unique claim appears here."
        claim_text = "A unique claim appears here."
        context = make_submit_context()
        result = ToolExecutorService().execute_tool(
            make_submit_call(
                draft=draft,
                claim_text=claim_text,
                start=0,
                end=len(claim_text),
            ),
            context,
        )
        assert result.result.status == "ok"
        assert result.submission is not None
        claim = result.submission.claims[0]
        assert (claim.draft_start, claim.draft_end) == (0, len(claim_text))

    def test_wrong_model_offsets_are_replaced_by_unique_exact_span(self):
        draft = "Prefix. A unique claim appears here."
        claim_text = "A unique claim appears here."
        context = make_submit_context()
        result = ToolExecutorService().execute_tool(
            make_submit_call(draft=draft, claim_text=claim_text, start=0, end=5),
            context,
        )
        assert result.result.status == "ok"
        assert result.submission is not None
        claim = result.submission.claims[0]
        assert draft[claim.draft_start:claim.draft_end] == claim_text
        assert claim.draft_end <= len(draft)

    def test_whitespace_and_markdown_are_handled_without_fuzzy_matching(self):
        draft = "*Current\ninformation* is available."
        claim_text = "Current information"
        context = make_submit_context()
        result = ToolExecutorService().execute_tool(
            make_submit_call(draft=draft, claim_text=claim_text, start=0, end=999),
            context,
        )
        assert result.result.status == "ok"
        assert result.submission is not None
        claim = result.submission.claims[0]
        assert draft[claim.draft_start:claim.draft_end] == "Current\ninformation"

    def test_ambiguous_repeated_text_is_rejected_without_guessing(self):
        draft = "Repeat. Repeat."
        context = make_submit_context()
        result = ToolExecutorService().execute_tool(
            make_submit_call(draft=draft, claim_text="Repeat.", start=0, end=7),
            context,
        )
        assert result.result.status == "invalid_request"
        assert result.submission is None
        assert result.submission_action is not None
        assert result.submission_action.can_continue is True
        assert result.result.data["errors"][0]["code"] == "CLAIM_TEXT_AMBIGUOUS"
        assert context.terminal_record.correction_count == 1

    def test_absent_or_paraphrased_text_is_rejected(self):
        draft = "Hello! How can I help you with Australian immigration today?"
        context = make_submit_context()
        result = ToolExecutorService().execute_tool(
            make_submit_call(
                draft=draft,
                claim_text="The assistant offers help with Australian immigration matters.",
                start=0,
                end=72,
            ),
            context,
        )
        assert result.result.status == "invalid_request"
        assert result.submission is None
        assert result.result.data["errors"][0]["code"] == "CLAIM_TEXT_NOT_FOUND"

    def test_unicode_claim_span_is_codepoint_safe_and_in_bounds(self):
        draft = "说明：签证申请需要材料。"
        claim_text = "签证申请需要材料。"
        context = make_submit_context()
        result = ToolExecutorService().execute_tool(
            make_submit_call(draft=draft, claim_text=claim_text, start=0, end=1),
            context,
        )
        assert result.result.status == "ok"
        assert result.submission is not None
        claim = result.submission.claims[0]
        assert draft[claim.draft_start:claim.draft_end] == claim_text
        assert 0 <= claim.draft_start <= claim.draft_end <= len(draft)

    async def test_rejected_submit_receives_one_bounded_repair_then_accepts(self):
        draft = "Hello!"
        invalid = make_submit_call(
            draft=draft,
            claim_text="A paraphrase that is not in the draft.",
            start=0,
            end=100,
        )
        valid = ToolCallRequest(
            call_id="submit-valid-after-repair",
            name="submit_answer",
            arguments={
                "schema_version": "agent_submission.v2",
                "answer_class": "general",
                "draft_markdown": draft,
                "claims": [],
                "citations": [],
                "research_status": "not_required",
                "state_patch": [],
            },
        )
        provider = MockProvider([
            ProviderResponse(response_id="invalid-submit", model="gpt-5.6-luna", status="ok", tool_calls=[invalid]),
            ProviderResponse(response_id="valid-submit", model="gpt-5.6-luna", status="ok", tool_calls=[valid]),
        ])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry("repair-test"),
        )
        assert result.status == "completed"
        assert result.metrics.provider_api_call_count == 2
        assert result.terminal_submission_continuation_count == 1
        assert result.tool_outputs[0].status == "invalid_request"
        assert result.tool_outputs[0].data["errors"][0]["code"] == "CLAIM_TEXT_NOT_FOUND"


# ---------------------------------------------------------------------------
# Tests: Shadow disabled
# ---------------------------------------------------------------------------


class TestShadowDisabled:
    def test_shadow_disabled_no_invocation(self):
        from app.core.config import get_settings
        settings = get_settings()
        assert settings.agent_shadow_enabled is False


# ---------------------------------------------------------------------------
# Tests: Public result independent of shadow
# ---------------------------------------------------------------------------


class TestShadowIsolation:
    async def test_shadow_result_does_not_affect_public(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.status == "completed"
        assert trace.submission is not None

    async def test_shadow_exception_isolated(self):
        provider = MagicMock(spec=ProviderInterface)
        provider.call = AsyncMock(side_effect=RuntimeError("Simulated failure"))
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.status == "error"

    async def test_shadow_timeout_isolated(self):
        provider = MockProvider([
            ProviderResponse(response_id="resp-slow", model="gpt-5.6-luna", status="timeout", duration_ms=40000),
        ])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.status in ("timeout", "error", "incomplete")


# ---------------------------------------------------------------------------
# Tests: Greeting / stable general
# ---------------------------------------------------------------------------


class TestGeneralConversation:
    async def test_greeting_no_research(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.status == "completed"
        assert result.submission.answer_class == "general"
        assert result.submission.research_status == "not_required"
        assert result.metrics.provider_api_call_count == 1

    async def test_stable_general_no_legal_retrieval(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="What is the capital of Australia?"),
            deadline=deadline, registry=registry,
        )
        assert result.status == "completed"
        assert result.metrics.flat_rag_call_count == 0


# ---------------------------------------------------------------------------
# Tests: Terminal submission
# ---------------------------------------------------------------------------


class TestTerminalSubmission:
    async def test_terminal_submit_success(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.status == "completed"
        assert result.terminal_submission_missing is False
        assert result.metrics.submit_answer_call_count == 1

    def test_tool_executor_propagates_accepted_submission_and_terminal_action(self):
        executor = ToolExecutorService()
        context = ToolExecutorContext(request_id="test-req", registry=create_registry())
        result = executor.execute_tool(
            ToolCallRequest(
                call_id="submit-call-1",
                name="submit_answer",
                arguments=make_greeting_response().tool_calls[0].arguments,
            ),
            context,
        )
        assert result.result.status == "ok"
        assert result.submission is not None
        assert result.submission_action is not None
        assert result.submission_action.action == "accept_submission"

    async def test_accepted_submit_does_not_make_acknowledgement_call(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry(),
        )
        assert result.status == "completed"
        assert result.submission is not None
        assert provider.call_count == 1

    async def test_rejected_submit_sends_matching_output_and_allows_one_repair(self):
        invalid_args = make_greeting_response().tool_calls[0].arguments | {
            "answer_class": "substantive_legal",
            "research_status": "not_required",
        }
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-invalid-submit",
                model="gpt-5.6-luna",
                status="ok",
                tool_calls=[ToolCallRequest(
                    call_id="submit-rejected-1", name="submit_answer", arguments=invalid_args,
                )],
            ),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry(),
        )
        assert result.status == "completed"
        assert provider.call_count == 2
        second_history = provider.call_args[1]["messages_history"]
        matching_outputs = [
            message for message in second_history
            if message.get("role") == "tool" and message.get("tool_call_id") == "submit-rejected-1"
        ]
        assert len(matching_outputs) == 1

    async def test_deterministic_utility_sends_matching_output_and_continues(self):
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-utility",
                model="gpt-5.6-luna",
                status="ok",
                tool_calls=[ToolCallRequest(
                    call_id="utility-call-1",
                    name="deterministic_utility",
                    arguments={"operation": "arithmetic", "operands": [1, 2], "expression": "1 + 2"},
                )],
            ),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Calculate 1 + 2"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry(),
        )
        assert result.status == "completed"
        assert provider.call_count == 2
        second_history = provider.call_args[1]["messages_history"]
        assert any(
            message.get("role") == "tool" and message.get("tool_call_id") == "utility-call-1"
            for message in second_history
        )

    async def test_one_missing_submit_continuation(self):
        provider = MockProvider([make_no_submit_response(), make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.terminal_submission_missing is True
        assert result.terminal_submission_continuation_count == 1
        assert result.metrics.provider_api_call_count == 2

    async def test_second_miss_failure(self):
        provider = MockProvider([make_no_submit_response(), make_no_submit_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry,
        )
        assert result.status in ("error", "incomplete")
        assert result.terminal_submission_missing is True


# ---------------------------------------------------------------------------
# Tests: Deadline
# ---------------------------------------------------------------------------


class TestDeadline:
    async def test_deadline_not_reset(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        started = time.perf_counter()
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000)
        initial = deadline.deadline_at
        await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert deadline.deadline_at == initial

    async def test_deadline_exceeded_stops_execution(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter() - 100, turn_deadline_ms=1)
        result = await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert result.status == "timeout"


# ---------------------------------------------------------------------------
# Tests: Budgets
# ---------------------------------------------------------------------------


class TestBudgets:
    async def test_max_provider_calls_enforced(self):
        provider = MockProvider([make_no_submit_response()] * 5)
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.provider_api_call_count <= 3

    async def test_retry_count_tracked(self):
        provider = MockProvider([
            ProviderResponse(response_id="resp-err", model="gpt-5.6-luna", status="error", duration_ms=100),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert result.metrics.retry_count >= 1

    async def test_inherited_execution_budget_honored(self):
        provider = MockProvider([make_no_submit_response(), make_no_submit_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=1, max_provider_calls=2, max_retries=0,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.provider_api_call_count <= 2

    async def test_continuation_cannot_reset_deadline(self):
        provider = MockProvider([make_no_submit_response(), make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        started = time.perf_counter()
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000)
        initial = deadline.deadline_at
        await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        assert deadline.deadline_at == initial


# ---------------------------------------------------------------------------
# Tests: Phase-5 resource governance (Flat-RAG bound + retry viability)
# ---------------------------------------------------------------------------


class TestPhase5ResourceGovernance:
    class _AdvancingProvider(ProviderInterface):
        """Provider whose call advances a controllable clock, simulating elapsed
        research time.  Returns responses in order; any excess returns a default
        ok response without submit."""

        def __init__(self, clock, responses, advance_ms_per_call=100.0):
            self.clock = clock
            self.responses = list(responses)
            self.call_count = 0
            self.advance_ms_per_call = advance_ms_per_call

        async def call(self, *, system_prompt, user_text, model, tools,
                       tool_choice="auto", reasoning_effort=None,
                       messages_history=None, timeout_ms,
                       registry=None, previous_response_id=None):
            self.call_count += 1
            if self.clock is not None:
                self.clock.advance_ms(self.advance_ms_per_call)
            if self.call_count <= len(self.responses):
                return self.responses[self.call_count - 1]
            return ProviderResponse(
                response_id=f"resp-{self.call_count}", model=model,
                status="ok", text="No submission.", duration_ms=0,
            )

    class _FakeClock:
        def __init__(self, value: float = 0.0) -> None:
            self.value = value

        def __call__(self) -> float:
            return self.value

        def advance_ms(self, ms: float) -> None:
            self.value += ms / 1000.0

    async def test_flat_rag_bounded_to_one_execution_per_run(self):
        """Arm B: when Luna emits 3 flat_rag_search calls in one response,
        only 1 may execute; the rest are denied with a deterministic envelope."""
        flat_rag_calls = [
            ToolCallRequest(call_id=f"flat-{i}", name="flat_rag_search",
                            arguments={"query": f"query {i}", "top_k": None, "preferred_source_types": None})
            for i in range(3)
        ]
        executed: list[str] = []

        def fake_flat_rag_search(**kwargs):
            executed.append(kwargs.get("query"))
            from app.tools.flat_rag_search import FlatRagResult
            return FlatRagResult(chunks=[], evidence_refs=[], debug={}, duration_ms=1.0)

        provider = MockProvider([
            ProviderResponse(response_id="resp-flat", model="gpt-5.6-luna", status="ok",
                             tool_calls=flat_rag_calls),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=1,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1,
            retry_viability_threshold_ms=8000,
        )
        result = await runtime.run_shadow(
            make_runtime_request(user_text="legal query", execution_budget=budget, experiment_arm="B"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry("flat-bound"),
            flat_rag_search_fn=fake_flat_rag_search,
        )
        # Only one actual execution happened.
        assert len(executed) == 1
        assert result.metrics.flat_rag_call_count == 1
        assert result.metrics.flat_rag_denied_call_count == 2
        # Denied calls surfaced to the provider so Luna can continue.
        denied = [t for t in result.tool_outputs if t.error and t.error.code == "FLAT_RAG_BUDGET_EXHAUSTED"]
        assert len(denied) == 2
        # The provider received a second call (the denied outputs were returned).
        assert provider.call_count == 2

    async def test_early_transient_failure_allows_one_bounded_retry(self):
        """The first provider call fails fast with plenty of budget left;
        one bounded retry is allowed."""
        provider = MockProvider([
            ProviderResponse(response_id="", model="gpt-5.6-luna", status="error", duration_ms=50),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000),
            registry=create_registry("retry-early"),
        )
        assert provider.call_count == 2
        assert result.metrics.retry_count >= 1
        assert result.metrics.provider_retry_skipped_reason is None

    async def test_late_failure_retry_skipped_when_remaining_below_threshold(self):
        """The first provider call starts while the 32s research stage is still
        valid, then fails late enough that no useful retry budget remains.  The
        retry is skipped; exactly one provider call occurs."""
        # Use a controllable clock so timing is deterministic and the first call
        # starts inside the 32s stage but consumes most of it.
        clock = self._FakeClock(value=0.0)
        # Absolute deadline = started_at + 40s.  Research stage = started_at + 32s.
        # First provider call advances 31s (stage still valid at start, but only
        # ~1s of 32s remains after it).  After the call, absolute remaining
        # ~9s (> 0) but research-stage remaining ~1s and < retry threshold 8s.
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[
                ProviderResponse(response_id="", model="gpt-5.6-luna", status="error", duration_ms=31000),
                make_greeting_response(),
            ],
            advance_ms_per_call=31000.0,
        )
        runtime = AgentRuntimeService(provider=provider)
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=1,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1,
            retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=budget),
            deadline=deadline,
            registry=create_registry("retry-late"),
        )
        # Exactly one provider call: it started while the 32s stage was valid.
        assert provider.call_count == 1
        # After the 31s call, research-stage remaining ~1s < retry threshold 8s,
        # so the retry is skipped.
        assert result.metrics.provider_retry_skipped_reason == "retry_viability_threshold_not_met"
        assert "retry skipped" in " ".join(result.errors).lower()

    async def test_deadline_remains_absolute_and_unchanged(self):
        """The resource-governance changes do not reset or extend the absolute
        deadline; the deadline object is unchanged across flat-RAG denials and
        retry viability checks."""
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-flat2", model="gpt-5.6-luna", status="ok",
                tool_calls=[
                    ToolCallRequest(call_id="f1", name="flat_rag_search",
                                    arguments={"query": "q", "top_k": None, "preferred_source_types": None}),
                    ToolCallRequest(call_id="f2", name="flat_rag_search",
                                    arguments={"query": "q2", "top_k": None, "preferred_source_types": None}),
                ],
            ),
            make_greeting_response(),
        ])

        def fake_flat_rag_search(**kwargs):
            from app.tools.flat_rag_search import FlatRagResult
            return FlatRagResult(chunks=[], evidence_refs=[], debug={}, duration_ms=1.0)

        runtime = AgentRuntimeService(provider=provider)
        started = time.perf_counter()
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000)
        initial = deadline.deadline_at
        result = await runtime.run_shadow(
            make_runtime_request(user_text="legal", execution_budget=ExecutionBudget(
                max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
                max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
            ), experiment_arm="B"),
            deadline=deadline,
            registry=create_registry("deadline-preserve"),
            flat_rag_search_fn=fake_flat_rag_search,
        )
        assert deadline.deadline_at == initial
        assert result.metrics.flat_rag_call_count == 1
        assert result.metrics.flat_rag_denied_call_count == 1

    def _make_utility_call(self, call_id: str) -> ProviderResponse:
        """A provider response emitting a legitimate nonterminal custom function
        call (deterministic_utility).  Executing it sends a function_call_output,
        which drives the REAL Responses function-output -> provider-continuation
        protocol for the next provider call (not a terminal submit repair)."""
        return ProviderResponse(
            response_id=f"resp-utility-{call_id}",
            model="gpt-5.6-luna",
            status="ok",
            tool_calls=[ToolCallRequest(
                call_id=call_id,
                name="deterministic_utility",
                arguments={
                    "operation": "arithmetic",
                    "operands": [1, 2],
                    "expression": "1 + 2",
                    "calendar": "calendar_days",
                    "timezone": "Australia/Sydney",
                    "rounding": "none",
                    "precision": 2,
                },
            )],
            duration_ms=100,
        )

    async def test_answer_research_budget_is_non_resetting_across_calls(self):
        """Multiple provider continuations triggered by a legitimate nonterminal
        custom function call (deterministic_utility -> function output) share the
        SAME non-resetting 32s research budget.  Once cumulative stage time
        reaches 32s the loop stops; a later continuation is not started."""
        clock = self._FakeClock(value=0.0)
        # Call 1 (stage 0s): emits deterministic_utility -> backend executes the
        # tool and appends a function_call_output -> provider continuation call 2.
        # Call 2 (stage ~20s): same utility call -> continuation call 3 would be
        # needed, but cumulative stage = ~40s > 32s so call 3 is blocked.
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[
                self._make_utility_call(call_id="util-call-1"),
                self._make_utility_call(call_id="util-call-2"),
            ],
            advance_ms_per_call=18000.0,
        )
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=0,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="legal", execution_budget=budget, experiment_arm="A"),
            deadline=deadline,
            registry=create_registry("stage-nonreset"),
        )
        # Call 1 (stage 0) runs and executes the FIRST utility.  Call 2
        # (continuation) starts at stage ~18s and requests a SECOND utility, but
        # by the time it is about to execute, cumulative stage = ~36s > 32s, so
        # the second utility MUST be denied and a third provider call never
        # starts.  Only the first utility executes.
        assert provider.call_count == 2
        assert result.metrics.provider_api_call_count == 2
        # Only the FIRST deterministic_utility executed; the second was blocked by
        # the exhausted 32s answer/research stage.
        assert result.metrics.utility_call_count == 1
        # Cumulative elapsed time exceeded the 32s stage but stayed within 40s.
        assert clock() >= 32.0
        assert clock() < 40.0
        # No third provider call occurred.
        assert provider.call_count == 2
        # No provider call/tool received a fresh 32s stage budget (the loop
        # stopped at stage exhaustion, not at the 40s absolute deadline).
        # The absolute 40s deadline was not reset.
        errs_lower = " ".join(result.errors).lower()
        assert any(k in errs_lower for k in (
            "answer/research stage", "deadline exceeded", "max tool rounds",
            "terminal submission",
        ))

    async def test_provider_continuation_blocked_after_stage_exhausted(self):
        """A provider continuation cannot start after the 32s answer/research
        stage budget is exhausted, even though the 40s absolute deadline remains."""
        clock = self._FakeClock()
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[make_no_submit_response()],
            advance_ms_per_call=33000.0,  # first call already consumes the stage
        )
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=0,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="legal", execution_budget=budget),
            deadline=deadline,
            registry=create_registry("stage-exhausted-continuation"),
        )
        # First provider call occurred exactly once.
        assert provider.call_count == 1
        # Fake clock advanced past the 32s research-stage boundary.
        assert clock() >= 32.0
        # The absolute turn still had ~7s remaining (well inside 40s).
        assert clock() < 40.0
        # The second continuation did NOT occur.
        assert result.metrics.provider_api_call_count == 1
        # A controlled terminal/stage/deadline error occurred (behavioral, not
        # one exact human-readable sentence).
        errs_lower = " ".join(result.errors).lower()
        assert any(k in errs_lower for k in (
            "answer/research stage", "deadline exceeded", "no continuation allowed",
            "terminal submission",
        ))

    async def test_early_retry_still_allowed_with_stage_budget(self):
        """A fast early transient failure still gets one bounded retry when both
        the absolute deadline and the stage budget have room."""
        clock = self._FakeClock()
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[
                ProviderResponse(response_id="", model="gpt-5.6-luna", status="error", duration_ms=50),
                make_greeting_response(),
            ],
            advance_ms_per_call=100.0,
        )
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=1,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=budget),
            deadline=deadline,
            registry=create_registry("stage-early-retry"),
        )
        assert provider.call_count == 2
        assert result.metrics.retry_count >= 1
        assert result.metrics.provider_retry_skipped_reason is None

    async def test_observability_records_ordered_provider_and_tool_observations(self):
        """Multiple provider calls generate ordered observations with correct
        classification, timeout allocation, stage-budget remainders, and tool
        timing; observability is content-free (no raw prompt/PII)."""
        clock = self._FakeClock(value=0.0)
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[
                self._make_utility_call(call_id="util-obs-1"),
                self._make_utility_call(call_id="util-obs-2"),
            ],
            advance_ms_per_call=18000.0,
        )
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=0,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="legal", execution_budget=budget, experiment_arm="A"),
            deadline=deadline,
            registry=create_registry("obs-diag"),
        )
        # Ordered provider observations.
        pcs = result.metrics.provider_calls
        assert len(pcs) == 2
        assert pcs[0].call_index == 1
        assert pcs[0].call_kind == "initial"
        assert pcs[1].call_index == 2
        assert pcs[1].call_kind in ("continuation",)
        # Timeout allocation and stage remainders observable.
        assert pcs[0].timeout_allocated_ms == 32000
        assert pcs[0].research_stage_remaining_before_ms == 32000
        assert pcs[1].research_stage_remaining_before_ms < 32000
        # Tool observations ordered & timed.
        tcs = result.metrics.tool_calls
        assert len(tcs) == 1  # only first utility executed; second denied by stage
        assert tcs[0].tool_name == "deterministic_utility"
        assert tcs[0].governor_denied is False
        assert tcs[0].duration_ms >= 0
        assert result.metrics.total_provider_duration_ms >= 0
        assert result.metrics.total_tool_duration_ms >= 0
        # Content-free: no raw user prompt or PII in serialized observations.
        blob = json.dumps([pc.model_dump(mode="json") for pc in pcs] + [tc.model_dump(mode="json") for tc in tcs])
        assert "legal" not in blob  # only our user_text is "legal"; ensure not stored
        assert "chain_of_thought" not in blob.lower()

    async def test_observability_classifies_retry(self):
        """A provider retry after an early transient failure is classified as
        'retry' with is_retry=True; the initial call is 'initial'."""
        clock = self._FakeClock(value=0.0)
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[
                ProviderResponse(response_id="", model="gpt-5.6-luna", status="error", duration_ms=50),
                make_greeting_response(),
            ],
            advance_ms_per_call=100.0,
        )
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=3, max_retries=1,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=budget),
            deadline=deadline,
            registry=create_registry("obs-retry"),
        )
        pcs = result.metrics.provider_calls
        assert len(pcs) == 2
        assert pcs[0].call_kind == "initial"
        assert pcs[0].status == "error"
        assert pcs[1].call_kind == "retry"
        assert pcs[1].is_retry is True

    async def test_multiple_short_calls_share_32s_budget_not_each_32s(self):
        """Twelve ~3s calls would consume ~36s; under a per-call timeout all 12
        would run.  Under the non-resetting stage budget the loop must stop at
        ~32s (10-11 calls), not run 12."""
        clock = self._FakeClock()
        provider = self._AdvancingProvider(
            clock=clock,
            responses=[make_no_submit_response()] * 12,
            advance_ms_per_call=3000.0,
        )
        budget = ExecutionBudget(
            max_tool_rounds=2, max_provider_calls=12, max_retries=0,
            turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            max_flat_rag_calls=1, retry_viability_threshold_ms=8000,
        )
        started = 0.0
        deadline = AbsoluteTurnDeadline(started_at=started, turn_deadline_ms=40000, clock=clock)
        runtime = AgentRuntimeService(provider=provider)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="legal", execution_budget=budget),
            deadline=deadline,
            registry=create_registry("stage-shared-32s"),
        )
        # 32s / 3s per call = up to 10 full calls + the blocked 11th attempt.
        assert provider.call_count < 12
        assert provider.call_count <= 11
        assert clock() < 40.0
        assert result.metrics.provider_api_call_count < 12


# ---------------------------------------------------------------------------
# Tests: PII guard
# ---------------------------------------------------------------------------


class TestPIIGuard:
    def test_clean_query_allowed(self):
        guard = SearchPrivacyGuard()
        assert guard.check_query("What are the Subclass 482 visa requirements?").allowed is True

    def test_email_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa for john.doe@example.com")
        assert result.allowed is False
        assert any("email" in v for v in result.violations)

    def test_passport_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa status for passport N12345678")
        assert result.allowed is False

    def test_phone_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Call 0412 345 678 about visa")
        assert result.allowed is False

    def test_dob_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("DOB: 15/06/1990 visa eligibility")
        assert result.allowed is False

    def test_trn_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Application EGOABC123456 status")
        assert result.allowed is False

    def test_legal_query_allowed(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Migration Regulations 1994 Schedule 2 criteria for Subclass 485 visa")
        assert result.allowed is True

    def test_sanitize_redacts_email(self):
        guard = SearchPrivacyGuard()
        result = guard.sanitize_query("Visa for john.doe@example.com application")
        assert result.allowed is True
        assert "john.doe@example.com" not in (result.sanitized_query or "")

    def test_name_indicator_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Client name is John Smith visa application")
        assert result.allowed is False

    def test_schedule_criteria_are_not_phones(self):
        for q in (
            "Schedule 3 criteria 3001 3002 3003 3004",
            "Migration Regulations Schedule 3 3001 3002 3003",
            "visa subclass 400 482 186 494",
            "Schedule 2 criterion 820.211 and Schedule 3 criteria 3001 3002",
            "Migration Act sections 100, 101, 102 of 1958",
        ):
            assert SearchPrivacyGuard().check_query(q).allowed is True

    def test_real_phone_pii_still_blocked(self):
        for q in (
            "Call 0401 234 567",
            "Phone (02) 9876 5432",
            "Contact +61 2 9876 5432",
            "Call +44 20 7946 0958",
        ):
            result = SearchPrivacyGuard().check_query(q)
            assert result.allowed is False
            assert result.violation_categories.get("phone", 0) >= 1


# ---------------------------------------------------------------------------
# Tests: Arm A and Arm B tools
# ---------------------------------------------------------------------------


class TestExperimentArms:
    def test_arm_a_tools(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default", experiment_arm="A")
        tool_names = policy_service.get_tool_names(policy)
        assert "web_search" in tool_names
        assert "deterministic_utility" in tool_names
        assert "submit_answer" in tool_names
        assert "flat_rag_search" not in tool_names
        assert "lightrag_search" not in tool_names

    def test_arm_b_tools(self):
        from app.core.config import Settings
        settings = Settings(DATABASE_URL="postgresql://test", OPENAI_API_KEY="test", FLAT_RAG_TOOL_ENABLED=True)
        policy_service = AgentPolicyService()
        with patch("app.services.agent_policy_service.get_settings", return_value=settings):
            policy = policy_service.build_policy(mode="default", experiment_arm="B")
        tool_names = policy_service.get_tool_names(policy)
        assert "web_search" in tool_names
        assert "flat_rag_search" in tool_names
        assert "deterministic_utility" in tool_names
        assert "submit_answer" in tool_names
        assert "lightrag_search" not in tool_names

    def test_no_lightrag(self):
        policy_service = AgentPolicyService()
        for arm in [None, "A", "B"]:
            policy = policy_service.build_policy(mode="default", experiment_arm=arm)
            assert "lightrag_search" not in policy_service.get_tool_names(policy)

    def test_no_phase6_checker(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default", experiment_arm="A")
        tool_names = policy_service.get_tool_names(policy)
        assert "legal_fact_check" not in tool_names
        assert "fact_check" not in tool_names


# ---------------------------------------------------------------------------
# Tests: Evidence / citations
# ---------------------------------------------------------------------------


class TestEvidenceAndCitations:
    def test_fabricated_url_rejected(self):
        registry = create_registry()
        assert not registry.is_registered("web:fake-ref-12345")

    def test_cross_request_ref_rejected(self):
        registry1 = create_registry()
        registry2 = create_registry()
        from app.schemas.evidence import NativeWebCitation, NativeWebEvidenceRef
        evidence = NativeWebEvidenceRef(
            evidence_origin="openai_web_native", evidence_ref="web:pending",
            source_type="web_page", source_authenticity="unverified", authority_kind="commentary",
            jurisdiction=None, binding_status="non_binding", court_or_tribunal_level=None,
            retrieved_at=datetime.now(timezone.utc), provenance_complete=True,
            search_call_id="search-1", url="https://example.com", title="Test",
            native_web_citation=NativeWebCitation(start_index=0, end_index=10),
            canonical_source_id=None, document_version=None, effective_from=None, effective_to=None,
            text=None, content_hash=None,
        )
        ref = registry1.register_native_web_evidence(evidence=evidence, tool_call_id="call-1")
        assert not registry2.is_registered(ref)

    def test_memory_only_legal_fails_postcondition(self):
        from app.services.evidence_postcondition_service import EvidencePostconditionService
        registry = create_registry()
        draft = "The 485 visa requires you to have held a 500 visa."
        submission = AgentSubmissionV2(
            schema_version="agent_submission.v2", answer_class="substantive_legal",
            draft_markdown=draft,
            claims=[AgentClaim(claim_id="c1", claim_type="legal_rule", materiality="decisive",
                               text=draft, draft_start=0, draft_end=len(draft), evidence_refs=[])],
            citations=[], research_status="complete", state_patch=[],
        )
        result = EvidencePostconditionService(registry).evaluate(submission)
        assert result.status == "failed"


# ---------------------------------------------------------------------------
# Tests: State patch isolation
# ---------------------------------------------------------------------------


class TestStatePatchIsolation:
    async def test_candidate_state_patch_not_applied(self):
        provider = MockProvider([ProviderResponse(
            response_id="resp-patch", model="gpt-5.6-luna", status="ok", text="",
            tool_calls=[ToolCallRequest(call_id="call_submit_patch", name="submit_answer", arguments={
                "schema_version": "agent_submission.v2", "answer_class": "general",
                "draft_markdown": "OK.", "claims": [], "citations": [],
                "research_status": "not_required",
                "state_patch": [{"op": "add", "path": "confirmed_facts.visa", "value": "482"}],
            })],
            duration_ms=300,
        )])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="I want a 482 visa", mode="default", experiment_arm="A",
            upstream_gate_allowed=True,
        )
        assert trace.candidate_state_patch is not None
        assert len(trace.candidate_state_patch) > 0


# ---------------------------------------------------------------------------
# Tests: Metrics
# ---------------------------------------------------------------------------


class TestMetrics:
    async def test_metrics_counters_correct(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(make_runtime_request(user_text="Hello"), deadline=deadline, registry=registry)
        metrics = result.metrics
        assert metrics.logical_llm_stage_count == 1
        assert metrics.provider_api_call_count >= 1
        assert metrics.submit_answer_call_count == 1
        assert metrics.turn_deadline_ms == 40000
        assert metrics.total_latency_ms > 0
        assert metrics.metrics_complete is True

    async def test_no_hidden_reasoning_persisted(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        trace_dict = {"trace_id": trace.trace_id, "status": trace.status, "errors": trace.errors}
        assert "chain_of_thought" not in str(trace_dict).lower()
        assert "hidden_reasoning" not in str(trace_dict).lower()


# ---------------------------------------------------------------------------
# Tests: Political gate
# ---------------------------------------------------------------------------


class TestPoliticalGate:
    def test_blocked_request_should_not_invoke_shadow(self):
        from app.core.config import get_settings
        assert get_settings().backend_political_failsafe_enabled is True

    async def test_shadow_blocked_without_upstream_gate(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=False,
        )
        assert trace.status == "blocked"
        assert "upstream political gate" in str(trace.errors).lower()

    async def test_shadow_allowed_with_upstream_gate(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert trace.status == "completed"


# ---------------------------------------------------------------------------
# Tests: No public AnswerTrace
# ---------------------------------------------------------------------------


class TestNoPublicAnswerTrace:
    async def test_shadow_does_not_create_public_trace(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert isinstance(trace, ShadowTrace)
        assert trace.trace_id is not None


# ---------------------------------------------------------------------------
# Tests: Tool executor
# ---------------------------------------------------------------------------


class TestToolExecutor:
    def test_execute_deterministic_utility(self):
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(request_id="test-req", registry=registry)
        result = executor.execute_tool(
            ToolCallRequest(call_id="call-1", name="deterministic_utility",
                            arguments={"operation": "arithmetic", "operands": [10, 20], "expression": "10 + 20"}),
            context,
        )
        assert result.result.status == "ok"

    def test_execute_unknown_tool(self):
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(request_id="test-req", registry=registry)
        result = executor.execute_tool(ToolCallRequest(call_id="call-1", name="nonexistent_tool", arguments={}), context)
        assert result.result.status == "invalid_request"

    def test_flat_rag_unavailable_without_fn(self):
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(request_id="test-req", registry=registry, flat_rag_search_fn=None)
        result = executor.execute_tool(
            ToolCallRequest(call_id="call-1", name="flat_rag_search", arguments={"query": "test"}), context,
        )
        assert result.result.status == "unavailable"


# ---------------------------------------------------------------------------
# Tests: Agent policy
# ---------------------------------------------------------------------------


class TestAgentPolicy:
    def test_default_mode_uses_luna(self):
        assert AgentPolicyService().build_policy(mode="default").model == "gpt-5.6-luna"

    def test_premium_mode_uses_sol(self):
        assert AgentPolicyService().build_policy(mode="premium").model == "gpt-5.6-sol"

    def test_tool_choice_is_auto(self):
        assert AgentPolicyService().build_policy(mode="default").tool_choice == "auto"

    def test_system_prompt_no_visa_routing(self):
        prompt_lower = AgentPolicyService().build_policy(mode="default").system_prompt.lower()
        for subclass in ("subclass 188", "subclass 485", "subclass 400", "subclass 482", "subclass 500", "subclass 820"):
            assert subclass not in prompt_lower


# ---------------------------------------------------------------------------
# Tests: Registry lifecycle
# ---------------------------------------------------------------------------


class TestRegistryLifecycle:
    async def test_evidence_captured_before_disposal(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert isinstance(trace.evidence_refs, list)

    async def test_registry_disposed_after_trace(self):
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello", mode="default", experiment_arm="A", upstream_gate_allowed=True,
        )
        assert trace.evidence_refs is not None

    async def test_shadow_uses_fresh_session_and_deep_copies_matter_state(self):
        original_state = {"topic": {"selected": "original"}}
        captured: dict[str, Any] = {}

        class FakeSession:
            closed = False

            def close(self):
                self.closed = True

        session = FakeSession()

        class CapturingRuntime(AgentRuntimeService):
            async def run_shadow(self, request, **kwargs):
                captured["request"] = request
                captured["db_session"] = kwargs["db_session"]
                request.matter_state["topic"]["selected"] = "shadow-only"
                return await super().run_shadow(request, **kwargs)

        runtime = CapturingRuntime(provider=MockProvider([make_greeting_response()]))
        shadow = ShadowAgentService(runtime)
        trace = await shadow.run_shadow(
            user_text="Hello",
            mode="default",
            matter_state=original_state,
            db_session_factory=lambda: session,
            experiment_arm="A",
            upstream_gate_allowed=True,
        )

        assert trace.status == "completed"
        assert captured["db_session"] is session
        assert session.closed is True
        assert captured["request"].matter_state["topic"]["selected"] == "shadow-only"
        assert original_state == {"topic": {"selected": "original"}}


# ---------------------------------------------------------------------------
# Tests: Provider adapter (mock-based)
# ---------------------------------------------------------------------------


class TestProviderAdapter:
    def test_provider_response_has_pii_violation_count(self):
        resp = ProviderResponse(response_id="test", model="gpt-5.6-luna", status="ok", text="Hello", pii_violation_count=0)
        assert resp.pii_violation_count == 0

    def test_mock_provider_returns_typed_response(self):
        provider = MockProvider([make_greeting_response()])
        async def _test():
            resp = await provider.call(
                system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000,
            )
            assert resp.status == "ok"
            assert resp.model == "gpt-5.6-luna"
            assert len(resp.tool_calls) == 1
            assert resp.tool_calls[0].name == "submit_answer"
        anyio.run(_test)

    def test_provider_response_with_web_search_tool_call(self):
        resp = ProviderResponse(
            response_id="test-web", model="gpt-5.6-luna", status="ok", text="Let me search...",
            tool_calls=[ToolCallRequest(call_id="call_web_1", name="web_search", arguments={"query": "Australian visa requirements"})],
        )
        assert len(resp.tool_calls) == 1
        assert resp.tool_calls[0].name == "web_search"

    def test_provider_response_with_multiple_turns(self):
        provider = MockProvider([
            ProviderResponse(response_id="turn-1", model="gpt-5.6-luna", status="ok", text="Researching...",
                             tool_calls=[ToolCallRequest(call_id="call_1", name="web_search", arguments={"query": "test"})]),
            make_greeting_response(),
        ])
        async def _test():
            resp1 = await provider.call(system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000)
            assert resp1.tool_calls[0].name == "web_search"
            resp2 = await provider.call(system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000)
            assert resp2.tool_calls[0].name == "submit_answer"
        anyio.run(_test)

    def test_responses_mixed_output_returns_only_custom_function_calls(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        class FakeResponses:
            def __init__(self):
                self.calls = []

            def create(self, **kwargs):
                self.calls.append(kwargs)
                return SimpleNamespace(
                    id="resp-mixed",
                    output=[
                        SimpleNamespace(
                            type="web_search_call",
                            id="search-1",
                            action=SimpleNamespace(queries=["Australian migration law"]),
                            sources=[],
                        ),
                        SimpleNamespace(
                            type="function_call",
                            call_id="utility-call-2",
                            name="deterministic_utility",
                            arguments='{"operation":"arithmetic","operands":[2,3],"expression":"2 + 3"}',
                        ),
                    ],
                )

        fake_responses = FakeResponses()
        adapter = OpenAIResponsesAdapter(client=SimpleNamespace(responses=fake_responses))

        async def _test():
            response = await adapter.call(
                system_prompt="test",
                user_text="test",
                model="gpt-5.6-luna",
                tools=[{"type": "web_search"}, {"type": "function", "name": "deterministic_utility"}],
                timeout_ms=1000,
                registry=create_registry(),
            )
            assert [call.call_id for call in response.tool_calls] == ["utility-call-2"]
            assert all(call.name != "web_search" for call in response.tool_calls)

        anyio.run(_test)

    def test_responses_registers_action_sources_and_annotations(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        url = "https://immi.homeaffairs.gov.au/visas/getting-a-visa/explore-visa-options"

        class FakeResponses:
            def __init__(self):
                self.calls = []

            def create(self, **kwargs):
                self.calls.append(kwargs)
                return SimpleNamespace(
                    id="resp-native-web",
                    output=[
                        SimpleNamespace(
                            type="web_search_call",
                            id="ws-native-1",
                            action=SimpleNamespace(
                                type="search",
                                queries=["Explore visa options"],
                                sources=[SimpleNamespace(type="url", url=url)],
                            ),
                        ),
                        SimpleNamespace(
                            type="message",
                            content=[SimpleNamespace(
                                type="output_text",
                                text="The page helps people explore visa options.",
                                annotations=[SimpleNamespace(
                                    type="url_citation",
                                    start_index=0,
                                    end_index=46,
                                    title="Explore visa options",
                                    url=url,
                                )],
                            )],
                        ),
                    ],
                )

        fake_responses = FakeResponses()
        adapter = OpenAIResponsesAdapter(client=SimpleNamespace(responses=fake_responses))
        registry = create_registry("native-web-adapter")

        async def _test():
            response = await adapter.call(
                system_prompt="test",
                user_text="test",
                model="gpt-5.6-luna",
                tools=[{"type": "web_search"}],
                timeout_ms=1000,
                registry=registry,
            )
            assert response.status == "ok"

        anyio.run(_test)
        refs = registry.get_all_refs()
        assert len(refs) == 1
        assert refs[0].startswith("web:")
        evidence = registry.resolve_evidence(refs[0])
        assert evidence.url == url
        assert evidence.title == "Explore visa options"
        assert evidence.search_call_id == "ws-native-1"
        assert evidence.provenance_complete is True
        assert evidence.native_web_citation is not None
        assert fake_responses.calls[0]["include"] == ["web_search_call.action.sources"]

    def test_responses_registers_source_without_fabricating_citation(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        class FakeResponses:
            def create(self, **kwargs):
                return SimpleNamespace(
                    id="resp-source-only",
                    output=[SimpleNamespace(
                        type="web_search_call",
                        id="ws-source-only",
                        action=SimpleNamespace(
                            type="search",
                            queries=["source only"],
                            sources=[SimpleNamespace(type="url", url="https://example.gov.au/page")],
                        ),
                    )],
                )

        registry = create_registry("native-web-source-only")
        adapter = OpenAIResponsesAdapter(
            client=SimpleNamespace(responses=FakeResponses())
        )

        async def _test():
            await adapter.call(
                system_prompt="test",
                user_text="test",
                model="gpt-5.6-luna",
                tools=[{"type": "web_search"}],
                timeout_ms=1000,
                registry=registry,
            )

        anyio.run(_test)
        refs = registry.get_all_refs()
        assert len(refs) == 1
        evidence = registry.resolve_evidence(refs[0])
        assert evidence.native_web_citation is None

    def test_responses_without_sources_or_annotations_registers_nothing(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        class FakeResponses:
            def create(self, **kwargs):
                return SimpleNamespace(
                    id="resp-no-native-web",
                    output=[SimpleNamespace(
                        type="web_search_call",
                        id="ws-no-native-web",
                        action=SimpleNamespace(type="search", queries=["no results"], sources=[]),
                    )],
                )

        registry = create_registry("native-web-empty")
        adapter = OpenAIResponsesAdapter(
            client=SimpleNamespace(responses=FakeResponses())
        )

        async def _test():
            await adapter.call(
                system_prompt="test",
                user_text="test",
                model="gpt-5.6-luna",
                tools=[{"type": "web_search"}],
                timeout_ms=1000,
                registry=registry,
            )

        anyio.run(_test)
        assert registry.get_all_refs() == []

    def test_responses_continuation_uses_exact_call_id_and_previous_response(self):
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter

        adapter = OpenAIResponsesAdapter(client=SimpleNamespace(responses=SimpleNamespace(create=lambda **_: SimpleNamespace(id="resp-2", output=[]))))
        items = adapter._build_input(
            system_prompt="test",
            previous_response_id="resp-1",
            messages_history=[
                {"role": "assistant", "content": "", "tool_calls": [{"id": "utility-call-3"}]},
                {"role": "tool", "tool_call_id": "utility-call-3", "content": "{\"status\":\"ok\"}"},
            ],
        )
        assert items == [{
            "type": "function_call_output",
            "call_id": "utility-call-3",
            "output": '{"status":"ok"}',
        }]

    def test_provider_missing_terminal_submit(self):
        resp = make_no_submit_response()
        assert len(resp.tool_calls) == 0
        assert resp.text is not None

    def test_provider_malformed_event_handled(self):
        resp = ProviderResponse(response_id="", model="", status="error")
        assert resp.status == "error"

    def test_mock_provider_accepts_registry_param(self):
        """MockProvider accepts the new registry and previous_response_id params."""
        provider = MockProvider([make_greeting_response()])
        registry = create_registry()
        async def _test():
            resp = await provider.call(
                system_prompt="test", user_text="test", model="gpt-5.6-luna", tools=[], timeout_ms=1000,
                registry=registry, previous_response_id="prev-123",
            )
            assert resp.status == "ok"
            # Verify call args include the new params
            assert provider.call_args[-1]["registry"] is registry
            assert provider.call_args[-1]["previous_response_id"] == "prev-123"
        anyio.run(_test)


# ---------------------------------------------------------------------------
# Tests: PII at provider boundary
# ---------------------------------------------------------------------------


class TestPIIProviderBoundary:
    def test_pii_query_blocked_before_provider(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa for john.doe@example.com status")
        assert result.allowed is False

    def test_clean_query_passes_provider_boundary(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Subclass 482 visa sponsorship requirements 2026")
        assert result.allowed is True

    def test_provider_response_tracks_pii_violations(self):
        resp = ProviderResponse(response_id="test", model="gpt-5.6-luna", status="ok", pii_violation_count=2)
        assert resp.pii_violation_count == 2


# ---------------------------------------------------------------------------
# Tests: Execution budget
# ---------------------------------------------------------------------------


class TestExecutionBudgetEnforcement:
    def test_execution_budget_validation(self):
        budget = ExecutionBudget(max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                                 turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000)
        assert budget.answer_research_target_ms + budget.checker_target_ms <= budget.turn_deadline_ms
        assert budget.max_flat_rag_calls == 1
        assert budget.retry_viability_threshold_ms == 8000

    def test_execution_budget_rejects_invalid(self):
        from pydantic import ValidationError
        try:
            ExecutionBudget(max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                            turn_deadline_ms=1000, answer_research_target_ms=32000, checker_target_ms=8000)
            assert False, "Should have raised"
        except ValidationError:
            pass

    def test_execution_budget_rejects_invalid_retry_threshold(self):
        from pydantic import ValidationError
        try:
            ExecutionBudget(
                max_tool_rounds=2, max_provider_calls=3, max_retries=1,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
                retry_viability_threshold_ms=50000,
            )
            assert False, "Should have raised"
        except ValidationError:
            pass

    async def test_lower_provider_cap_honored(self):
        provider = MockProvider([make_no_submit_response()] * 4)
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=2, max_provider_calls=2, max_retries=0,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.provider_api_call_count <= 2

    async def test_lower_tool_round_cap_honored(self):
        provider = MockProvider([
            ProviderResponse(response_id="r1", model="gpt-5.6-luna", status="ok",
                             tool_calls=[ToolCallRequest(call_id="c1", name="web_search", arguments={"query": "test"})]),
            ProviderResponse(response_id="r2", model="gpt-5.6-luna", status="ok",
                             tool_calls=[ToolCallRequest(call_id="c2", name="web_search", arguments={"query": "test2"})]),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(started_at=time.perf_counter(), turn_deadline_ms=40000)
        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello", execution_budget=ExecutionBudget(
                max_tool_rounds=1, max_provider_calls=3, max_retries=0,
                turn_deadline_ms=40000, answer_research_target_ms=32000, checker_target_ms=8000,
            )), deadline=deadline, registry=registry,
        )
        assert result.metrics.tool_round_count <= 1


# ---------------------------------------------------------------------------
# Tests: Route-level (real QueryRequest schema)
# ---------------------------------------------------------------------------


class TestRouteIntegration:
    """Route-level tests using the real QueryRequest schema."""

    def test_query_request_has_question_field(self):
        """QueryRequest uses 'question' not 'user_text'."""
        req = QueryRequest(question="Hello, I need visa help")
        assert req.question == "Hello, I need visa help"

    def test_query_request_defaults(self):
        """QueryRequest has correct defaults."""
        req = QueryRequest(question="Test question")
        assert req.assistant_mode == "default_legal_pipeline"
        assert req.response_language is None

    def test_shadow_disabled_route_returns_legacy(self):
        """When shadow is disabled, route returns legacy response normally."""
        from app.core.config import get_settings
        settings = get_settings()
        assert settings.agent_shadow_enabled is False
        # Route integration: shadow disabled means no background task scheduled

    def test_no_mock_fallback_in_production_path(self):
        """Production shadow path uses OpenAIResponsesAdapter, not MockProvider."""
        # The _schedule_shadow_run function imports OpenAIResponsesAdapter directly
        # and does NOT catch ImportError to fall back to MockProvider
        from app.services.openai_responses_adapter import OpenAIResponsesAdapter
        assert OpenAIResponsesAdapter is not None

    def test_background_task_uses_fresh_db_session(self):
        """Background task creates its own SessionLocal, doesn't retain request session."""
        # Verified by code review: _run_shadow() calls SessionLocal() internally
        # and closes it in finally. The request-scoped db is never passed in.
        pass  # Design invariant verified by code structure

    def test_political_blocked_no_background_task(self):
        """Political blocked requests never schedule shadow."""
        # Verified by code review: _schedule_shadow_run is only called when
        # settings.agent_shadow_enabled and not politically_blocked
        pass  # Design invariant verified by code structure


# ---------------------------------------------------------------------------
# Tests: Native evidence flow (end-to-end mocked)
# ---------------------------------------------------------------------------


class TestNativeEvidenceFlow:
    """End-to-end native evidence flow through registry."""

    def test_web_search_normalization_registers_evidence(self):
        """WebEvidenceNormalizer registers native web evidence in registry."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        registry = create_registry()
        normalizer = WebEvidenceNormalizer()

        search_output = {
            "sources": [
                {
                    "url": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-489",
                    "title": "Skilled Regional visa (subclass 489)",
                    "citation": {"start_index": 10, "end_index": 50},
                }
            ]
        }

        results = normalizer.normalize_search_output(
            search_output=search_output,
            search_call_id="search-1",
            tool_call_id="call-1",
            registry=registry,
        )

        assert len(results) == 1
        evidence, ref = results[0]
        assert ref.startswith("web:")
        assert registry.is_registered(ref)

    def test_registered_evidence_resolvable(self):
        """Registered evidence can be resolved within the same request."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        registry = create_registry()
        normalizer = WebEvidenceNormalizer()

        search_output = {
            "sources": [
                {
                    "url": "https://www.legislation.gov.au/Details/C2026C00001",
                    "title": "Migration Act 1958",
                    "citation": {"start_index": 0, "end_index": 100},
                }
            ]
        }

        results = normalizer.normalize_search_output(
            search_output=search_output,
            search_call_id="search-1",
            tool_call_id="call-1",
            registry=registry,
        )

        ref = results[0][1]
        evidence = registry.resolve_evidence(ref)
        assert evidence.url == "https://www.legislation.gov.au/Details/C2026C00001"

    def test_cross_request_evidence_not_resolvable(self):
        """Evidence from one request cannot be resolved in another."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        registry1 = create_registry()
        registry2 = create_registry()
        normalizer = WebEvidenceNormalizer()

        results = normalizer.normalize_search_output(
            search_output={"sources": [{"url": "https://example.com/page", "title": "Test",
                                         "citation": {"start_index": 0, "end_index": 10}}]},
            search_call_id="search-1", tool_call_id="call-1", registry=registry1,
        )

        ref = results[0][1]
        assert registry1.is_registered(ref)
        assert not registry2.is_registered(ref)

    def test_submission_can_reference_registered_evidence(self):
        """submit_answer can reference evidence registered in the same request."""
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer
        from app.services.agent_submission_validator import AgentSubmissionValidator

        registry = create_registry()
        normalizer = WebEvidenceNormalizer()

        results = normalizer.normalize_search_output(
            search_output={"sources": [{"url": "https://example.com/page", "title": "Test",
                                         "citation": {"start_index": 0, "end_index": 10}}]},
            search_call_id="search-1", tool_call_id="call-1", registry=registry,
        )

        ref = results[0][1]
        draft = "Based on official guidance, the visa requires..."
        submission = AgentSubmissionV2(
            schema_version="agent_submission.v2", answer_class="substantive_legal",
            draft_markdown=draft,
            claims=[AgentClaim(claim_id="c1", claim_type="legal_rule", materiality="decisive",
                               text=draft, draft_start=0, draft_end=len(draft),
                               evidence_refs=[ref])],
            citations=[{"evidence_ref": ref, "display_label": "Official guidance"}],
            research_status="complete", state_patch=[],
        )

        validator = AgentSubmissionValidator(registry)
        result = validator.validate(submission)
        assert result.valid is True

    def test_registry_disposed_after_evidence_capture(self):
        """Registry is disposed but evidence was already captured in trace."""
        registry = create_registry()
        refs_before = registry.get_all_refs()
        registry.dispose()
        # After disposal, get_all_refs returns empty
        assert registry.is_disposed is True
        # But we already captured refs_before disposal
        assert isinstance(refs_before, list)

    def test_provider_tokens_are_rejected_and_registered_refs_are_exposed_for_repair(self):
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer

        registry = create_registry("repair-native-web")
        draft = "The page helps people explore visa options."
        ref = WebEvidenceNormalizer().normalize_search_output(
            search_output={"sources": [{
                "url": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/explore-visa-options",
                "title": "Explore visa options",
                "citation": {"start_index": 0, "end_index": len(draft)},
            }]},
            search_call_id="ws-repair-1",
            tool_call_id="ws-repair-1",
            registry=registry,
        )[0][1]

        current_date = datetime.now(timezone.utc).date()
        context = ToolExecutorContext(
            request_id="repair-native-web",
            registry=registry,
            as_of_date=current_date,
        )
        executor = ToolExecutorService()
        base_arguments = {
            "schema_version": "agent_submission.v2",
            "answer_class": "procedural",
            "draft_markdown": draft,
            "as_of_date": current_date.isoformat(),
            "claims": [{
                "claim_id": "c1",
                "claim_type": "current_fact",
                "materiality": "decisive",
                "text": draft,
                "draft_start": 0,
                "draft_end": len(draft),
                "evidence_refs": ["turn0search1"],
            }],
            "citations": [{"evidence_ref": "turn0search1", "display_label": "Explore visa options"}],
            "research_status": "complete",
            "state_patch": [],
        }
        first = executor.execute_tool(
            ToolCallRequest(call_id="submit-first", name="submit_answer", arguments=base_arguments),
            context,
        )
        assert first.result.status == "invalid_request"
        assert first.result.data["errors"][0]["code"] == "INVALID_EVIDENCE_REF_FORMAT"
        assert first.result.data["available_evidence_refs"] == [ref]
        assert first.result.data["available_native_web_evidence"][0]["evidence_ref"] == ref
        repair = first.result.data.get("repair_instruction", "")
        assert "native_web_locators" in repair
        assert "controlling" in repair
        assert "exact-text" in repair or "exact text" in repair
        assert "native_web_citation is non-null" not in repair

        repaired = dict(base_arguments)
        repaired["claims"] = [dict(base_arguments["claims"][0], evidence_refs=[ref])]
        repaired["citations"] = [{"evidence_ref": ref, "display_label": "Explore visa options"}]
        second = executor.execute_tool(
            ToolCallRequest(call_id="submit-repaired", name="submit_answer", arguments=repaired),
            context,
        )
        assert second.result.status == "ok"
        assert second.submission_action is not None
        assert second.submission_action.action == "accept_submission"

    def test_repair_cannot_remove_decisive_claims_while_claiming_complete_research(self):
        from app.services.web_evidence_normalizer import WebEvidenceNormalizer

        registry = create_registry("repair-claim-removal")
        draft = "The page helps people explore visa options."
        ref = WebEvidenceNormalizer().normalize_search_output(
            search_output={"sources": [{
                "url": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/explore-visa-options",
                "title": "Explore visa options",
                "citation": {"start_index": 0, "end_index": len(draft)},
            }]},
            search_call_id="ws-claim-removal",
            tool_call_id="ws-claim-removal",
            registry=registry,
        )[0][1]
        context = ToolExecutorContext(
            request_id="repair-claim-removal",
            registry=registry,
            as_of_date=datetime.now(timezone.utc).date(),
        )
        executor = ToolExecutorService()
        first_args = {
            "schema_version": "agent_submission.v2",
            "answer_class": "procedural",
            "draft_markdown": draft,
            "as_of_date": datetime.now(timezone.utc).date().isoformat(),
            "claims": [{
                "claim_id": "c1", "claim_type": "current_fact", "materiality": "decisive",
                "text": draft, "draft_start": 0, "draft_end": len(draft),
                "evidence_refs": ["turn0search1"],
            }],
            "citations": [{"evidence_ref": "turn0search1", "display_label": "Explore visa options"}],
            "research_status": "complete", "state_patch": [],
        }
        executor.execute_tool(
            ToolCallRequest(call_id="claim-removal-first", name="submit_answer", arguments=first_args),
            context,
        )
        repaired_args = dict(first_args, claims=[], citations=[{"evidence_ref": ref, "display_label": "Explore visa options"}])
        repaired = executor.execute_tool(
            ToolCallRequest(call_id="claim-removal-second", name="submit_answer", arguments=repaired_args),
            context,
        )
        assert repaired.result.status == "invalid_request"
        assert repaired.result.data["errors"][0]["code"] == "REPAIR_REMOVED_REQUIRED_CLAIMS"
