"""Phase 5 — Luna shadow agent unit/mock tests.

Tests cover:
- Shadow disabled → no invocation
- Public result independent of shadow result
- Shadow exception isolated
- Shadow timeout isolated
- Greeting → no unnecessary research
- Stable general → no legal retrieval
- Current general can select web
- Legal memory-only result fails
- Native citation normalization flow
- Fabricated URL rejected
- Cross-request ref rejected
- Terminal submit success
- One missing-submit continuation
- Second miss failure
- Deadline not reset
- Provider/tool/retry budgets enforced
- PII query blocked before outbound execution
- Candidate state patch not applied
- No public AnswerTrace generated by shadow
- Political-blocked request cannot reach shadow
- Arm A tools correct
- Arm B tools correct
- No LightRAG
- No Phase-6 checker
- Metrics counters correct
- No hidden reasoning persisted

All tests use MOCKED provider outputs. No live OpenAI calls.
"""

from __future__ import annotations

import time
from datetime import date, datetime, timezone
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4


from app.schemas.agent import (
    AgentClaim,
    AgentRuntimeRequest,
    AgentSubmissionV2,
    ExecutionBudget,
)
from app.services.agent_observability_service import (
    AbsoluteTurnDeadline,
)
from app.services.agent_policy_service import (
    AgentPolicyService,
)
from app.services.agent_runtime_service import (
    AgentRuntimeService,
    ProviderInterface,
    ProviderResponse,
)
from app.services.request_evidence_registry import (
    create_registry,
)
from app.services.search_privacy_guard import SearchPrivacyGuard
from app.services.shadow_agent_service import ShadowAgentService, ShadowTrace
from app.services.tool_executor_service import (
    ToolCallRequest,
    ToolExecutorContext,
    ToolExecutorService,
)


# ---------------------------------------------------------------------------
# Mock provider
# ---------------------------------------------------------------------------


class MockProvider(ProviderInterface):
    """Mock provider that returns pre-configured responses."""

    def __init__(self, responses: list[ProviderResponse] | None = None) -> None:
        self.responses = responses or []
        self.call_count = 0
        self.call_args: list[dict[str, Any]] = []

    async def call(
        self,
        *,
        system_prompt: str,
        user_text: str,
        model: str,
        tools: list[dict[str, Any]],
        tool_choice: str = "auto",
        messages_history: list[dict[str, Any]] | None = None,
        timeout_ms: float,
    ) -> ProviderResponse:
        self.call_count += 1
        self.call_args.append({
            "system_prompt": system_prompt,
            "user_text": user_text,
            "model": model,
            "tools": tools,
            "tool_choice": tool_choice,
            "messages_history": messages_history,
            "timeout_ms": timeout_ms,
        })
        if self.call_count <= len(self.responses):
            return self.responses[self.call_count - 1]
        # Default: return text without submit_answer
        return ProviderResponse(
            response_id=f"resp-{self.call_count}",
            model=model,
            status="ok",
            text="Here is a general answer without submission.",
            duration_ms=100,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_greeting_response() -> ProviderResponse:
    """Mock response for a greeting — direct submit_answer, no research."""
    return ProviderResponse(
        response_id="resp-greeting",
        model="gpt-5.6-luna",
        status="ok",
        text="",
        tool_calls=[
            ToolCallRequest(
                call_id="call_submit_1",
                name="submit_answer",
                arguments={
                    "schema_version": "agent_submission.v2",
                    "answer_class": "general",
                    "draft_markdown": "Hello! How can I help you with Australian immigration today?",
                    "as_of_date": None,
                    "claims": [],
                    "citations": [],
                    "research_status": "not_required",
                    "state_patch": [],
                },
            )
        ],
        duration_ms=500,
    )


def make_legal_response_with_web_search() -> list[ProviderResponse]:
    """Two-step: web search then submit_answer."""
    return [
        ProviderResponse(
            response_id="resp-legal-1",
            model="gpt-5.6-luna",
            status="ok",
            text="Let me research that.",
            tool_calls=[
                ToolCallRequest(
                    call_id="call_web_1",
                    name="web_search",
                    arguments={"query": "Subclass 482 visa requirements 2026"},
                )
            ],
            duration_ms=800,
        ),
        ProviderResponse(
            response_id="resp-legal-2",
            model="gpt-5.6-luna",
            status="ok",
            text="",
            tool_calls=[
                ToolCallRequest(
                    call_id="call_submit_2",
                    name="submit_answer",
                    arguments={
                        "schema_version": "agent_submission.v2",
                        "answer_class": "substantive_legal",
                        "draft_markdown": "The Subclass 482 visa requires...",
                        "as_of_date": "2026-08-18",
                        "claims": [
                            {
                                "claim_id": "c1",
                                "claim_type": "legal_rule",
                                "materiality": "decisive",
                                "text": "The Subclass 482 visa requires",
                                "draft_start": 0,
                                "draft_end": 30,
                                "evidence_refs": [],
                            }
                        ],
                        "citations": [],
                        "research_status": "complete",
                        "state_patch": [],
                    },
                )
            ],
            duration_ms=600,
        ),
    ]


def make_memory_only_legal_response() -> ProviderResponse:
    """Legal answer from memory — no tools, no evidence."""
    return ProviderResponse(
        response_id="resp-memory",
        model="gpt-5.6-luna",
        status="ok",
        text="",
        tool_calls=[
            ToolCallRequest(
                call_id="call_submit_mem",
                name="submit_answer",
                arguments={
                    "schema_version": "agent_submission.v2",
                    "answer_class": "substantive_legal",
                    "draft_markdown": "The 485 visa requires you to have held a 500 visa.",
                    "as_of_date": "2026-08-18",
                    "claims": [
                        {
                            "claim_id": "c1",
                            "claim_type": "legal_rule",
                            "materiality": "decisive",
                            "text": "The 485 visa requires you to have held a 500 visa.",
                            "draft_start": 0,
                            "draft_end": 56,
                            "evidence_refs": [],
                        }
                    ],
                    "citations": [],
                    "research_status": "complete",
                    "state_patch": [],
                },
            )
        ],
        duration_ms=300,
    )


def make_no_submit_response() -> ProviderResponse:
    """Response without submit_answer."""
    return ProviderResponse(
        response_id="resp-no-submit",
        model="gpt-5.6-luna",
        status="ok",
        text="Here is some information about Australian immigration...",
        duration_ms=500,
    )


def make_runtime_request(**overrides: Any) -> AgentRuntimeRequest:
    defaults: dict[str, Any] = {
        "request_id": str(uuid4()),
        "turn_id": str(uuid4()),
        "mode": "default",
        "user_text": "Hello",
        "response_language": "en",
        "as_of_date": date.today(),
        "matter_state": {},
        "execution_budget": ExecutionBudget(
            max_tool_rounds=2,
            max_provider_calls=3,
            max_retries=1,
            turn_deadline_ms=40000,
            answer_research_target_ms=32000,
            checker_target_ms=8000,
        ),
        "experiment_arm": None,
    }
    defaults.update(overrides)
    return AgentRuntimeRequest(**defaults)


# ---------------------------------------------------------------------------
# Tests: Shadow disabled
# ---------------------------------------------------------------------------


class TestShadowDisabled:
    """Shadow must not run when AGENT_SHADOW_ENABLED is false."""

    def test_shadow_disabled_no_invocation(self):
        """When shadow is disabled, no shadow run should be initiated."""
        from app.core.config import get_settings

        settings = get_settings()
        # Default is False — verify
        assert settings.agent_shadow_enabled is False


# ---------------------------------------------------------------------------
# Tests: Public result independent of shadow
# ---------------------------------------------------------------------------


class TestShadowIsolation:
    """Shadow result must never affect public answer."""

    async def test_shadow_result_does_not_affect_public(self):
        """Shadow run completes but public answer is independent."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)

        # Run shadow
        trace = await shadow.run_shadow(
            user_text="Hello",
            mode="default",
            experiment_arm="A",
        )

        # Shadow completed
        assert trace.status == "completed"
        assert trace.submission is not None

        # But public answer is NOT affected — this is just a trace
        # (In production, the public V1 path runs independently)
        assert trace.candidate_state_patch is not None or trace.candidate_state_patch == []

    async def test_shadow_exception_isolated(self):
        """Shadow exception does not propagate to caller."""
        provider = MagicMock(spec=ProviderInterface)
        provider.call = AsyncMock(side_effect=RuntimeError("Simulated failure"))
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)

        # Should not raise
        trace = await shadow.run_shadow(
            user_text="Hello",
            mode="default",
            experiment_arm="A",
        )

        assert trace.status == "error"
        assert "Simulated failure" in str(trace.errors)

    async def test_shadow_timeout_isolated(self):
        """Shadow timeout does not affect public path."""
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-slow",
                model="gpt-5.6-luna",
                status="timeout",
                duration_ms=40000,
            )
        ])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)

        trace = await shadow.run_shadow(
            user_text="Hello",
            mode="default",
            experiment_arm="A",
        )

        # Should complete with timeout status
        assert trace.status in ("timeout", "error", "incomplete")


# ---------------------------------------------------------------------------
# Tests: Greeting / stable general
# ---------------------------------------------------------------------------


class TestGeneralConversation:
    """General conversation should not trigger unnecessary research."""

    async def test_greeting_no_research(self):
        """Greeting should use one provider call, no research tools."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        assert result.status == "completed"
        assert result.submission is not None
        assert result.submission.answer_class == "general"
        assert result.submission.research_status == "not_required"
        # One provider call, no web search
        assert result.metrics.provider_api_call_count == 1
        assert result.metrics.web_search_call_count == 0

    async def test_stable_general_no_legal_retrieval(self):
        """Stable general knowledge should not trigger legal tools."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="What is the capital of Australia?"),
            deadline=deadline,
            registry=registry,
        )

        assert result.status == "completed"
        assert result.metrics.flat_rag_call_count == 0
        assert result.metrics.exact_lookup_call_count == 0


# ---------------------------------------------------------------------------
# Tests: Terminal submission
# ---------------------------------------------------------------------------


class TestTerminalSubmission:
    """Terminal submit_answer contract tests."""

    async def test_terminal_submit_success(self):
        """Valid submit_answer terminates successfully."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        assert result.status == "completed"
        assert result.submission is not None
        assert result.terminal_submission_missing is False
        assert result.metrics.submit_answer_call_count == 1

    async def test_one_missing_submit_continuation(self):
        """First missing submit_answer gets one continuation."""
        # First response: no submit_answer
        # Second response (after continuation): submit_answer
        provider = MockProvider([
            make_no_submit_response(),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        # Should have received continuation and then submitted
        assert result.terminal_submission_missing is True
        assert result.terminal_submission_continuation_count == 1
        assert result.metrics.provider_api_call_count == 2

    async def test_second_miss_failure(self):
        """Second missing submit_answer fails closed."""
        # Both responses: no submit_answer
        provider = MockProvider([
            make_no_submit_response(),
            make_no_submit_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        # Should fail after second miss
        assert result.status in ("error", "incomplete")
        assert result.terminal_submission_missing is True
        assert result.terminal_submission_continuation_count >= 1


# ---------------------------------------------------------------------------
# Tests: Deadline
# ---------------------------------------------------------------------------


class TestDeadline:
    """Absolute deadline tests."""

    async def test_deadline_not_reset(self):
        """Deadline is never reset during execution."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        started = time.perf_counter()
        deadline = AbsoluteTurnDeadline(
            started_at=started,
            turn_deadline_ms=40000,
        )

        initial_deadline_at = deadline.deadline_at

        await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        # Deadline should not have changed
        assert deadline.deadline_at == initial_deadline_at

    async def test_deadline_exceeded_stops_execution(self):
        """When deadline is exceeded, execution stops."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        # Deadline already in the past
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter() - 100,
            turn_deadline_ms=1,  # 1ms deadline, already exceeded
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        assert result.status == "timeout"
        assert result.metrics.deadline_exceeded_stage is not None


# ---------------------------------------------------------------------------
# Tests: Budgets
# ---------------------------------------------------------------------------


class TestBudgets:
    """Provider/tool/retry budget enforcement."""

    async def test_max_provider_calls_enforced(self):
        """Max provider calls is enforced."""
        # Return no-submit repeatedly to force continuations
        provider = MockProvider([
            make_no_submit_response(),
            make_no_submit_response(),
            make_no_submit_response(),
            make_no_submit_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(
                user_text="Hello",
                execution_budget=ExecutionBudget(
                    max_tool_rounds=2,
                    max_provider_calls=3,
                    max_retries=1,
                    turn_deadline_ms=40000,
                    answer_research_target_ms=32000,
                    checker_target_ms=8000,
                ),
            ),
            deadline=deadline,
            registry=registry,
        )

        # Should not exceed max_provider_calls
        assert result.metrics.provider_api_call_count <= 3

    async def test_retry_count_tracked(self):
        """Retry count is correctly tracked."""
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-err",
                model="gpt-5.6-luna",
                status="error",
                duration_ms=100,
            ),
            make_greeting_response(),
        ])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        # First call was error, second succeeded
        assert result.metrics.retry_count >= 1


# ---------------------------------------------------------------------------
# Tests: PII guard
# ---------------------------------------------------------------------------


class TestPIIGuard:
    """Search privacy guard tests."""

    def test_clean_query_allowed(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("What are the Subclass 482 visa requirements?")
        assert result.allowed is True

    def test_email_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa for john.doe@example.com")
        assert result.allowed is False
        assert any("email" in v for v in result.violations)

    def test_passport_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Visa status for passport N12345678")
        assert result.allowed is False
        assert any("passport" in v for v in result.violations)

    def test_phone_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Call 0412 345 678 about visa")
        assert result.allowed is False
        assert any("phone" in v for v in result.violations)

    def test_dob_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("DOB: 15/06/1990 visa eligibility")
        assert result.allowed is False
        assert any("date of birth" in v.lower() for v in result.violations)

    def test_trn_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Application EGOABC123456 status")
        assert result.allowed is False
        assert any("TRN" in v for v in result.violations)

    def test_legal_query_allowed(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query(
            "Migration Regulations 1994 Schedule 2 criteria for Subclass 485 visa"
        )
        assert result.allowed is True

    def test_sanitize_redacts_email(self):
        guard = SearchPrivacyGuard()
        result = guard.sanitize_query("Visa for john.doe@example.com application")
        assert result.allowed is True
        assert "john.doe@example.com" not in (result.sanitized_query or "")

    def test_name_indicator_blocked(self):
        guard = SearchPrivacyGuard()
        result = guard.check_query("Client name is John Smith visa application")
        assert result.allowed is False


# ---------------------------------------------------------------------------
# Tests: Arm A and Arm B tools
# ---------------------------------------------------------------------------


class TestExperimentArms:
    """Arm A and Arm B tool configuration."""

    def test_arm_a_tools(self):
        """Arm A: web_search + deterministic_utility + submit_answer."""
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default", experiment_arm="A")

        tool_names = policy_service.get_tool_names(policy)
        assert "web_search" in tool_names
        assert "deterministic_utility" in tool_names
        assert "submit_answer" in tool_names
        assert "flat_rag_search" not in tool_names
        assert "lightrag_search" not in tool_names

    def test_arm_b_tools(self):
        """Arm B: web_search + flat_rag_search + deterministic_utility + submit_answer."""
        from app.core.config import Settings

        # Create a Settings instance with flat_rag_tool_enabled=True
        settings = Settings(
            DATABASE_URL="postgresql://test",
            OPENAI_API_KEY="test",
            FLAT_RAG_TOOL_ENABLED=True,
        )
        policy_service = AgentPolicyService()

        # Patch get_settings where it's imported in agent_policy_service
        with patch("app.services.agent_policy_service.get_settings", return_value=settings):
            policy = policy_service.build_policy(mode="default", experiment_arm="B")

        tool_names = policy_service.get_tool_names(policy)
        assert "web_search" in tool_names
        assert "flat_rag_search" in tool_names
        assert "deterministic_utility" in tool_names
        assert "submit_answer" in tool_names
        assert "lightrag_search" not in tool_names

    def test_no_lightrag(self):
        """LightRAG is never included in Phase 5."""
        policy_service = AgentPolicyService()
        for arm in [None, "A", "B"]:
            policy = policy_service.build_policy(mode="default", experiment_arm=arm)
            tool_names = policy_service.get_tool_names(policy)
            assert "lightrag_search" not in tool_names

    def test_no_phase6_checker(self):
        """No checker tool in Phase 5."""
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default", experiment_arm="A")
        tool_names = policy_service.get_tool_names(policy)
        assert "legal_fact_check" not in tool_names
        assert "fact_check" not in tool_names


# ---------------------------------------------------------------------------
# Tests: Evidence / citations
# ---------------------------------------------------------------------------


class TestEvidenceAndCitations:
    """Evidence and citation validation."""

    def test_fabricated_url_rejected(self):
        """Model-typed URL is not valid evidence."""
        registry = create_registry()
        # A URL that was never registered
        assert not registry.is_registered("web:fake-ref-12345")

    def test_cross_request_ref_rejected(self):
        """Evidence from another request is rejected."""
        registry1 = create_registry()
        registry2 = create_registry()

        # Register in registry1
        from app.schemas.evidence import NativeWebCitation, NativeWebEvidenceRef

        evidence = NativeWebEvidenceRef(
            evidence_origin="openai_web_native",
            evidence_ref="web:pending",
            source_type="web_page",
            source_authenticity="unverified",
            authority_kind="commentary",
            jurisdiction=None,
            binding_status="non_binding",
            court_or_tribunal_level=None,
            retrieved_at=datetime.now(timezone.utc),
            provenance_complete=True,
            search_call_id="search-1",
            url="https://example.com",
            title="Test",
            native_web_citation=NativeWebCitation(start_index=0, end_index=10),
            canonical_source_id=None,
            document_version=None,
            effective_from=None,
            effective_to=None,
            text=None,
            content_hash=None,
        )
        ref = registry1.register_native_web_evidence(
            evidence=evidence, tool_call_id="call-1"
        )

        # Should not be in registry2
        assert not registry2.is_registered(ref)

    def test_memory_only_legal_fails_postcondition(self):
        """Legal claim with no evidence refs fails postcondition."""
        from app.services.evidence_postcondition_service import EvidencePostconditionService

        registry = create_registry()
        draft = "The 485 visa requires you to have held a 500 visa."
        submission = AgentSubmissionV2(
            schema_version="agent_submission.v2",
            answer_class="substantive_legal",
            draft_markdown=draft,
            claims=[
                AgentClaim(
                    claim_id="c1",
                    claim_type="legal_rule",
                    materiality="decisive",
                    text=draft,
                    draft_start=0,
                    draft_end=len(draft),
                    evidence_refs=[],
                )
            ],
            citations=[],
            research_status="complete",
            state_patch=[],
        )

        postcondition = EvidencePostconditionService(registry)
        result = postcondition.evaluate(submission)

        assert result.status == "failed"


# ---------------------------------------------------------------------------
# Tests: State patch isolation
# ---------------------------------------------------------------------------


class TestStatePatchIsolation:
    """Candidate state patch must not be applied to real Matter."""

    async def test_candidate_state_patch_not_applied(self):
        """State patch is recorded in shadow trace but not applied."""
        provider = MockProvider([
            ProviderResponse(
                response_id="resp-patch",
                model="gpt-5.6-luna",
                status="ok",
                text="",
                tool_calls=[
                    ToolCallRequest(
                        call_id="call_submit_patch",
                        name="submit_answer",
                        arguments={
                            "schema_version": "agent_submission.v2",
                            "answer_class": "general",
                            "draft_markdown": "OK.",
                            "claims": [],
                            "citations": [],
                            "research_status": "not_required",
                            "state_patch": [
                                {"op": "add", "path": "confirmed_facts.visa", "value": "482"}
                            ],
                        },
                    )
                ],
                duration_ms=300,
            )
        ])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)

        trace = await shadow.run_shadow(
            user_text="I want a 482 visa",
            mode="default",
            experiment_arm="A",
        )

        # State patch is recorded
        assert trace.candidate_state_patch is not None
        assert len(trace.candidate_state_patch) > 0

        # But it's only in the shadow trace — not applied to any real Matter
        # (In production, the real Matter is never touched by shadow)


# ---------------------------------------------------------------------------
# Tests: Metrics
# ---------------------------------------------------------------------------


class TestMetrics:
    """Metrics counters are correct."""

    async def test_metrics_counters_correct(self):
        """All metrics counters are populated correctly."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        registry = create_registry()
        deadline = AbsoluteTurnDeadline(
            started_at=time.perf_counter(),
            turn_deadline_ms=40000,
        )

        result = await runtime.run_shadow(
            make_runtime_request(user_text="Hello"),
            deadline=deadline,
            registry=registry,
        )

        metrics = result.metrics
        assert metrics.logical_llm_stage_count == 1
        assert metrics.provider_api_call_count >= 1
        assert metrics.tool_call_count >= 1  # submit_answer
        assert metrics.submit_answer_call_count == 1
        assert metrics.turn_deadline_ms == 40000
        assert metrics.total_latency_ms > 0
        assert metrics.metrics_complete is True

    async def test_no_hidden_reasoning_persisted(self):
        """Shadow trace does not contain chain of thought or hidden reasoning."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)

        trace = await shadow.run_shadow(
            user_text="Hello",
            mode="default",
            experiment_arm="A",
        )

        # Shadow trace should not contain reasoning
        trace_dict = {
            "trace_id": trace.trace_id,
            "status": trace.status,
            "errors": trace.errors,
        }
        # No chain_of_thought, no hidden_reasoning fields
        assert "chain_of_thought" not in str(trace_dict).lower()
        assert "hidden_reasoning" not in str(trace_dict).lower()


# ---------------------------------------------------------------------------
# Tests: Political gate
# ---------------------------------------------------------------------------


class TestPoliticalGate:
    """Political-blocked requests must not reach shadow."""

    def test_blocked_request_should_not_invoke_shadow(self):
        """This is a design invariant — tested in integration."""
        # In the FastAPI route, political gate runs BEFORE shadow dispatch.
        # If decision == "block", shadow is never invoked.
        # This test verifies the invariant is documented.
        from app.core.config import get_settings

        settings = get_settings()
        # Political failsafe must be enabled
        assert settings.backend_political_failsafe_enabled is True
        # Shadow is downstream of political gate in the route


# ---------------------------------------------------------------------------
# Tests: No public AnswerTrace
# ---------------------------------------------------------------------------


class TestNoPublicAnswerTrace:
    """Shadow must not create public AnswerTrace."""

    async def test_shadow_does_not_create_public_trace(self):
        """Shadow trace is isolated, not a public AnswerTrace."""
        provider = MockProvider([make_greeting_response()])
        runtime = AgentRuntimeService(provider=provider)
        shadow = ShadowAgentService(runtime)

        trace = await shadow.run_shadow(
            user_text="Hello",
            mode="default",
            experiment_arm="A",
        )

        # ShadowTrace is a separate type from AnswerTrace
        assert isinstance(trace, ShadowTrace)
        # It has a trace_id but is not in the lawyer review queue
        assert trace.trace_id is not None


# ---------------------------------------------------------------------------
# Tests: Tool executor
# ---------------------------------------------------------------------------


class TestToolExecutor:
    """Tool executor service tests."""

    def test_execute_deterministic_utility(self):
        """Deterministic utility executes correctly."""
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(
            request_id="test-req",
            registry=registry,
        )

        result = executor.execute_tool(
            ToolCallRequest(
                call_id="call-1",
                name="deterministic_utility",
                arguments={
                    "operation": "arithmetic",
                    "operands": [10, 20],
                    "expression": "10 + 20",
                },
            ),
            context,
        )

        assert result.result.status == "ok"

    def test_execute_unknown_tool(self):
        """Unknown tool returns invalid_request."""
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(
            request_id="test-req",
            registry=registry,
        )

        result = executor.execute_tool(
            ToolCallRequest(
                call_id="call-1",
                name="nonexistent_tool",
                arguments={},
            ),
            context,
        )

        assert result.result.status == "invalid_request"

    def test_flat_rag_unavailable_without_fn(self):
        """Flat RAG returns unavailable when function not injected."""
        executor = ToolExecutorService()
        registry = create_registry()
        context = ToolExecutorContext(
            request_id="test-req",
            registry=registry,
            flat_rag_search_fn=None,
        )

        result = executor.execute_tool(
            ToolCallRequest(
                call_id="call-1",
                name="flat_rag_search",
                arguments={"query": "test"},
            ),
            context,
        )

        assert result.result.status == "unavailable"


# ---------------------------------------------------------------------------
# Tests: Agent policy
# ---------------------------------------------------------------------------


class TestAgentPolicy:
    """Agent policy service tests."""

    def test_default_mode_uses_luna(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default")
        assert policy.model == "gpt-5.6-luna"

    def test_premium_mode_uses_sol(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="premium")
        assert policy.model == "gpt-5.6-sol"

    def test_tool_choice_is_auto(self):
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default")
        assert policy.tool_choice == "auto"

    def test_system_prompt_no_visa_routing(self):
        """System prompt must not contain visa-specific routing instructions."""
        policy_service = AgentPolicyService()
        policy = policy_service.build_policy(mode="default")

        # Check for absence of visa-specific routing
        prompt_lower = policy.system_prompt.lower()
        # Should NOT contain specific visa subclass routing
        assert "subclass 188" not in prompt_lower
        assert "subclass 485" not in prompt_lower
        assert "subclass 400" not in prompt_lower
        assert "subclass 482" not in prompt_lower
        assert "subclass 500" not in prompt_lower
        assert "subclass 820" not in prompt_lower
