import type { SiteLocale } from "@/lib/site-locale";

export const consultationCopy = {
  "zh-CN": {
    history: "我的咨询请求",
    newTitle: "提交咨询请求",
    detail: "咨询请求详情",
    create: "提交请求",
    addWindow: "添加时间偏好",
    removeWindow: "移除此时间偏好",
    timezone: "设备时区",
    noTimezone: "无法读取有效的设备时区，请检查设备或浏览器的时区设置。",
    loading: "正在加载咨询信息…",
    method: "咨询方式偏好（尚未确认）",
    other: "其他",
    note: "补充说明（可选）",
    start: "开始时间",
    end: "结束时间",
    unknownStatus: "状态待更新",
    requested: "已提交",
    proposed: "已收到时间提议",
    confirmed: "已确认",
    completed: "已完成",
    cancelled: "已取消",
    video: "视频",
    phone: "电话",
    in_person: "当面",
    no_preference: "无偏好",
    assignedYes: "已分配",
    assignedNo: "尚未分配",
    unavailable: "咨询功能暂不可用。请稍后再试。",
    empty: "暂无咨询请求。",
    loadError: "无法加载咨询信息，请稍后重试。",
    validation: "请填写至少一个有效的未来时间段，并检查结束时间。",
    submitError: "无法提交请求。请检查填写内容后重试。",
    auth: "请登录已验证的客户账户以继续。",
    stale: "此咨询已在其他位置更新。请查看最新状态后再继续。",
    confirm: "确认时间",
    reschedule: "请求改期",
    cancel: "取消请求",
    cancelConfirm: "确定取消此咨询请求吗？",
    assigned: "律师分配状态",
    windows: "偏好时间段",
    scheduled: "提议 / 已安排时间",
    scheduledMethod: "已安排方式",
    instructions: "会议信息",
    created: "创建时间",
    updated: "更新时间",
    proposedAt: "提议时间",
    confirmedAt: "确认时间",
    completedAt: "完成时间",
    cancelledAt: "取消时间",
    back: "返回咨询记录",
    newLink: "提交新的咨询请求",
    actionError: "操作未完成，请刷新后重试。",
    preferenceNote: "所选方式仅为偏好；最终安排将在后续确认。",
    emptyWindow: "请至少添加一个时间偏好。",
    customerNote: "客户备注",
  },
  en: {
    history: "My consultation requests",
    newTitle: "Submit a consultation request",
    detail: "Consultation request details",
    create: "Submit request",
    addWindow: "Add preferred time",
    removeWindow: "Remove this preference",
    timezone: "Device timezone",
    noTimezone:
      "A valid device timezone could not be detected. Check your device or browser timezone settings.",
    loading: "Loading consultation information…",
    method: "Preferred consultation method (not confirmed)",
    other: "Other",
    note: "Additional note (optional)",
    start: "Start time",
    end: "End time",
    unknownStatus: "Status update unavailable",
    requested: "Requested",
    proposed: "Time proposed",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    video: "Video",
    phone: "Phone",
    in_person: "In person",
    no_preference: "No preference",
    assignedYes: "Assigned",
    assignedNo: "Not yet assigned",
    unavailable:
      "Consultation requests are not available right now. Please try again later.",
    empty: "You have no consultation requests yet.",
    loadError:
      "Consultation information could not be loaded. Please try again.",
    validation:
      "Add at least one valid future time window and check its end time.",
    submitError:
      "The request could not be submitted. Check the form and try again.",
    auth: "Sign in to a verified customer account to continue.",
    stale:
      "This consultation was updated elsewhere. Review the latest state before continuing.",
    confirm: "Confirm time",
    reschedule: "Request rescheduling",
    cancel: "Cancel request",
    cancelConfirm: "Cancel this consultation request?",
    assigned: "Lawyer assignment",
    windows: "Preferred time windows",
    scheduled: "Proposed / scheduled time",
    scheduledMethod: "Scheduled method",
    instructions: "Meeting instructions",
    created: "Created",
    updated: "Updated",
    proposedAt: "Proposed",
    confirmedAt: "Confirmed",
    completedAt: "Completed",
    cancelledAt: "Cancelled",
    back: "Back to consultation history",
    newLink: "Submit another consultation request",
    actionError: "The action could not be completed. Refresh and try again.",
    preferenceNote:
      "This is a preference only; the final arrangement will be confirmed later.",
    emptyWindow: "Add at least one preferred time window.",
    customerNote: "Customer note",
  },
} as const;

export function getConsultationCopy(locale: SiteLocale) {
  return consultationCopy[locale];
}
